



export const GET_STOK_BATCH = "GET_STOK_BATCH"
export const GET_STOK_BATCH_SUCCESS = "GET_STOK_BATCH_SUCCESS"
export const GET_STOK_BATCH_ERROR = "GET_STOK_BATCH_ERROR"

export const CREATE_OR_UPDATE_ORDER_BARANG = "CREATE_OR_UPDATE_ORDER_BARANG"
export const CREATE_OR_UPDATE_ORDER_BARANG_SUCCESS = "CREATE_OR_UPDATE_ORDER_BARANG_SUCCESS"
export const CREATE_OR_UPDATE_ORDER_BARANG_ERROR = "CREATE_OR_UPDATE_ORDER_BARANG_ERROR"

export const GET_ORDER_BARANG = "GET_ORDER_BARANG"
export const GET_ORDER_BARANG_SUCCESS = "GET_ORDER_BARANG_SUCCESS"
export const GET_ORDER_BARANG_ERROR = "GET_ORDER_BARANG_ERROR"

export const GET_ORDER_STOK_BATCH = "GET_ORDER_STOK_BATCH"
export const GET_ORDER_STOK_BATCH_SUCCESS = "GET_ORDER_STOK_BATCH_SUCCESS"
export const GET_ORDER_STOK_BATCH_ERROR = "GET_ORDER_STOK_BATCH_ERROR"

export const CREATE_OR_UPDATE_KIRIM_BARANG = "CREATE_OR_UPDATE_KIRIM_BARANG"
export const CREATE_OR_UPDATE_KIRIM_BARANG_SUCCESS = "CREATE_OR_UPDATE_KIRIM_BARANG_SUCCESS"
export const CREATE_OR_UPDATE_KIRIM_BARANG_ERROR = "CREATE_OR_UPDATE_KIRIM_BARANG_ERROR"

export const VERIFY_KIRIM = "DISTRIBUSI/VERIFY_KIRIM"
export const VERIFY_KIRIM_SUCCESS = "DISTRIBUSI/VERIFY_KIRIM_SUCCESS"
export const VERIFY_KIRIM_ERROR = "DISTRIBUSI/VERIFY_KIRIM_ERROR"

export const TOLAK_ORDER = "DISTRIBUSI/TOLAK_ORDER"
export const TOLAK_ORDER_SUCCESS = "DISTRIBUSI/TOLAK_ORDER_SUCCESS"
export const TOLAK_ORDER_ERROR = "DISTRIBUSI/TOLAK_ORDER_ERROR"

export const TOLAK_KIRIM = "DISTRIBUSI/TOLAK_KIRIM"
export const TOLAK_KIRIM_SUCCESS = "DISTRIBUSI/TOLAK_KIRIM_SUCCESS"
export const TOLAK_KIRIM_ERROR = "DISTRIBUSI/TOLAK_KIRIM_ERROR"

