

export const GET_COMBO_TAMBAH_LAYANAN = "MDL/GET_COMBO_TAMBAH_LAYANAN"
export const GET_COMBO_TAMBAH_LAYANAN_SUCCESS = "MDL/GET_COMBO_TAMBAH_LAYANAN_SUCCESS"
export const GET_COMBO_TAMBAH_LAYANAN_ERROR = "MDL/GET_COMBO_TAMBAH_LAYANAN_ERROR"

export const UPSERT_LAYANAN = "MDL/UPSERT_LAYANAN"
export const UPSERT_LAYANAN_SUCCESS = "MDL/UPSERT_LAYANAN_SUCCESS"
export const UPSERT_LAYANAN_ERROR = "MDL/UPSERT_LAYANAN_ERROR"

export const GET_LAYANAN = "MDL/GET_LAYANAN"
export const GET_LAYANAN_SUCCESS = "MDL/GET_LAYANAN_SUCCESS"
export const GET_LAYANAN_ERROR = "MDL/GET_LAYANAN_ERROR"

export const GET_COMBO_MAP_RUANG_PELAYANAN = "MDL/GET_COMBO_MAP_RUANG_PELAYANAN"
export const GET_COMBO_MAP_RUANG_PELAYANAN_SUCCESS = "MDL/GET_COMBO_MAP_RUANG_PELAYANAN_SUCCESS"
export const GET_COMBO_MAP_RUANG_PELAYANAN_ERROR = "MDL/GET_COMBO_MAP_RUANG_PELAYANAN_ERROR"

export const GET_MAP_UNIT_TO_PRODUK = "MDL/GET_MAP_UNIT_TO_PRODUK"
export const GET_MAP_UNIT_TO_PRODUK_SUCCESS = "MDL/GET_MAP_UNIT_TO_PRODUK_SUCCESS"
export const GET_MAP_UNIT_TO_PRODUK_ERROR = "MDL/GET_MAP_UNIT_TO_PRODUK_ERROR"

export const GET_LAYANAN_MAPPING = "MDL/GET_LAYANAN_MAPPING"
export const GET_LAYANAN_MAPPING_SUCCESS = "MDL/GET_LAYANAN_MAPPING_SUCCESS"
export const GET_LAYANAN_MAPPING_ERROR = "MDL/GET_LAYANAN_MAPPING_ERROR"

export const SAVE_OR_DELETE_MAPPING = "MDL/SAVE_OR_DELETE_MAPPING"
export const SAVE_OR_DELETE_MAPPING_SUCCESS = "MDL/SAVE_OR_DELETE_MAPPING_SUCCESS"
export const SAVE_OR_DELETE_MAPPING_ERROR = "MDL/SAVE_OR_DELETE_MAPPING_ERROR"

export const GET_LAIN_LAIN = "MDL/GET_LAIN_LAIN"
export const GET_LAIN_LAIN_SUCCESS = "MDL/GET_LAIN_LAIN_SUCCESS"
export const GET_LAIN_LAIN_ERROR = "MDL/GET_LAIN_LAIN_ERROR"

export const UPSERT_JENIS_PRODUK = "MDL/UPSERT_JENIS_PRODUK"
export const UPSERT_JENIS_PRODUK_SUCCESS = "MDL/UPSERT_JENIS_PRODUK_SUCCESS"
export const UPSERT_JENIS_PRODUK_ERROR = "MDL/UPSERT_JENIS_PRODUK_ERROR"

export const UPSERT_DETAIL_JENIS_PRODUK = "MDL/UPSERT_DETAIL_JENIS_PRODUK"
export const UPSERT_DETAIL_JENIS_PRODUK_SUCCESS = "MDL/UPSERT_DETAIL_JENIS_PRODUK_SUCCESS"
export const UPSERT_DETAIL_JENIS_PRODUK_ERROR = "MDL/UPSERT_DETAIL_JENIS_PRODUK_ERROR"