

export const GET_COMBO_TAMBAH_LAYANAN = "MDL/GET_COMBO_TAMBAH_LAYANAN"
export const GET_COMBO_TAMBAH_LAYANAN_SUCCESS = "MDL/GET_COMBO_TAMBAH_LAYANAN_SUCCESS"
export const GET_COMBO_TAMBAH_LAYANAN_ERROR = "MDL/GET_COMBO_TAMBAH_LAYANAN_ERROR"

export const UPSERT_LAYANAN = "MDL/UPSERT_LAYANAN"
export const UPSERT_LAYANAN_SUCCESS = "MDL/UPSERT_LAYANAN_SUCCESS"
export const UPSERT_LAYANAN_ERROR = "MDL/UPSERT_LAYANAN_ERROR"

export const GET_LAYANAN = "MDL/GET_LAYANAN"
export const GET_LAYANAN_SUCCESS = "MDL/GET_LAYANAN_SUCCESS"
export const GET_LAYANAN_ERROR = "MDL/GET_LAYANAN_ERROR"

