export const EMR_RESET_FORM = "EMR_RESET_FORM";

export const EMR_HEADER_GET = "EMR_HEADER_GET";
export const EMR_HEADER_GET_SUCCESS = "EMR_HEADER_GET_SUCCESS";
export const EMR_HEADER_GET_ERROR = "EMR_HEADER_GET_ERROR";