export const EMR_RESET_FORM = "EMR_RESET_FORM";

export const EMR_HEADER_GET = "EMR_HEADER_GET";
export const EMR_HEADER_GET_SUCCESS = "EMR_HEADER_GET_SUCCESS";
export const EMR_HEADER_GET_ERROR = "EMR_HEADER_GET_ERROR";

export const EMR_TTV_SAVE = "EMR_TTV_SAVE";
export const EMR_TTV_SAVE_SUCCESS = "EMR_TTV_SAVE_SUCCESS";
export const EMR_TTV_SAVE_ERROR = "EMR_TTV_SAVE_ERROR";

export const EMR_TTV_GET = "EMR_TTV_GET";
export const EMR_TTV_GET_SUCCESS = "EMR_TTV_GET_SUCCESS";
export const EMR_TTV_GET_ERROR = "EMR_TTV_GET_ERROR";

export const EMR_SAVE = "EMR_SAVE";
export const EMR_SAVE_SUCCESS = "EMR_SAVE_SUCCESS";
export const EMR_SAVE_ERROR = "EMR_SAVE_ERROR";

export const EMR_GET = "EMR_GET";
export const EMR_GET_SUCCESS = "EMR_GET_SUCCESS";
export const EMR_GET_ERROR = "EMR_GET_ERROR";

export const EMR_COMBO_GET = "EMR_COMBO_GET";
export const EMR_COMBO_GET_SUCCESS = "EMR_COMBO_GET_SUCCESS";
export const EMR_COMBO_GET_ERROR = "EMR_COMBO_GET_ERROR";

export const EMR_DIAGNOSAX_GET = "EMR_DIAGNOSAX_GET";
export const EMR_DIAGNOSAX_GET_SUCCESS = "EMR_DIAGNOSAX_GET_SUCCESS";
export const EMR_DIAGNOSAX_GET_ERROR = "EMR_DIAGNOSAX_GET_ERROR";

export const EMR_DIAGNOSAIX_GET = "EMR_DIAGNOSAIX_GET";
export const EMR_DIAGNOSAIX_GET_SUCCESS = "EMR_DIAGNOSAIX_GET_SUCCESS";
export const EMR_DIAGNOSAIX_GET_ERROR = "EMR_DIAGNOSAIX_GET_ERROR";

export const EMR_DIAGNOSAX_SAVE = "EMR_DIAGNOSAX_SAVE";
export const EMR_DIAGNOSAX_SAVE_SUCCESS = "EMR_DIAGNOSAX_SAVE_SUCCESS";
export const EMR_DIAGNOSAX_SAVE_ERROR = "EMR_DIAGNOSAX_SAVE_ERROR";

export const EMR_DIAGNOSAIX_SAVE = "EMR_DIAGNOSAIX_SAVE";
export const EMR_DIAGNOSAIX_SAVE_SUCCESS = "EMR_DIAGNOSAIX_SAVE_SUCCESS";
export const EMR_DIAGNOSAIX_SAVE_ERROR = "EMR_DIAGNOSAIX_SAVE_ERROR";