export const EMR_RESET_FORM = "EMR_RESET_FORM";

export const EMR_HEADER_GET = "EMR_HEADER_GET";
export const EMR_HEADER_GET_SUCCESS = "EMR_HEADER_GET_SUCCESS";
export const EMR_HEADER_GET_ERROR = "EMR_HEADER_GET_ERROR";

export const EMR_TTV_SAVE = "EMR_TTV_SAVE";
export const EMR_TTV_SAVE_SUCCESS = "EMR_TTV_SAVE_SUCCESS";
export const EMR_TTV_SAVE_ERROR = "EMR_TTV_SAVE_ERROR";

export const EMR_TTV_GET = "EMR_TTV_GET";
export const EMR_TTV_GET_SUCCESS = "EMR_TTV_GET_SUCCESS";
export const EMR_TTV_GET_ERROR = "EMR_TTV_GET_ERROR";

export const EMR_SAVE = "EMR_SAVE";
export const EMR_SAVE_SUCCESS = "EMR_SAVE_SUCCESS";
export const EMR_SAVE_ERROR = "EMR_SAVE_ERROR";

export const EMR_GET = "EMR_GET";
export const EMR_GET_SUCCESS = "EMR_GET_SUCCESS";
export const EMR_GET_ERROR = "EMR_GET_ERROR";

export const EMR_COMBO_GET = "EMR_COMBO_GET";
export const EMR_COMBO_GET_SUCCESS = "EMR_COMBO_GET_SUCCESS";
export const EMR_COMBO_GET_ERROR = "EMR_COMBO_GET_ERROR";

export const EMR_DIAGNOSAX_GET = "EMR_DIAGNOSAX_GET";
export const EMR_DIAGNOSAX_GET_SUCCESS = "EMR_DIAGNOSAX_GET_SUCCESS";
export const EMR_DIAGNOSAX_GET_ERROR = "EMR_DIAGNOSAX_GET_ERROR";

export const EMR_DIAGNOSAIX_GET = "EMR_DIAGNOSAIX_GET";
export const EMR_DIAGNOSAIX_GET_SUCCESS = "EMR_DIAGNOSAIX_GET_SUCCESS";
export const EMR_DIAGNOSAIX_GET_ERROR = "EMR_DIAGNOSAIX_GET_ERROR";

export const EMR_DIAGNOSAX_SAVE = "EMR_DIAGNOSAX_SAVE";
export const EMR_DIAGNOSAX_SAVE_SUCCESS = "EMR_DIAGNOSAX_SAVE_SUCCESS";
export const EMR_DIAGNOSAX_SAVE_ERROR = "EMR_DIAGNOSAX_SAVE_ERROR";

export const EMR_DIAGNOSAIX_SAVE = "EMR_DIAGNOSAIX_SAVE";
export const EMR_DIAGNOSAIX_SAVE_SUCCESS = "EMR_DIAGNOSAIX_SAVE_SUCCESS";
export const EMR_DIAGNOSAIX_SAVE_ERROR = "EMR_DIAGNOSAIX_SAVE_ERROR";

export const EMR_LISTDIAGNOSAX_GET = "EMR_LISTDIAGNOSAX_GET";
export const EMR_LISTDIAGNOSAX_GET_SUCCESS = "EMR_LISTDIAGNOSAX_GET_SUCCESS";
export const EMR_LISTDIAGNOSAX_GET_ERROR = "EMR_LISTDIAGNOSAX_GET_ERROR";

export const EMR_LISTDIAGNOSAIX_GET = "EMR_LISTDIAGNOSAIX_GET";
export const EMR_LISTDIAGNOSAIX_GET_SUCCESS = "EMR_LISTDIAGNOSAIX_GET_SUCCESS";
export const EMR_LISTDIAGNOSAIX_GET_ERROR = "EMR_LISTDIAGNOSAIX_GET_ERROR";

/**
 * Delete PRODUCT
 */
export const DELETE_DIAGNOSAX = "DELETE_DIAGNOSAX"
export const DELETE_DIAGNOSAX_SUCCESS = "DELETE_DIAGNOSAX_SUCCESS"
export const DELETE_DIAGNOSAX_ERROR = "DELETE_DIAGNOSAX_ERROR"

/**
 * Delete PRODUCT
 */
export const DELETE_DIAGNOSAIX = "DELETE_DIAGNOSAIX"
export const DELETE_DIAGNOSAIX_SUCCESS = "DELETE_DIAGNOSAIX_SUCCESS"
export const DELETE_DIAGNOSAIX_ERROR = "DELETE_DIAGNOSAIX_ERROR"
// Konsul
export const KONSUL_SAVE = "KONSUL_SAVE";
export const KONSUL_SAVE_SUCCESS = "KONSUL_SAVE_SUCCESS";
export const KONSUL_SAVE_ERROR = "KONSUL_SAVE_ERROR";

// update TaskId
export const UPDATE_TASKID = "UPDATE_TASKID";
export const UPDATE_TASKID_SUCCESS = "UPDATE_TASKID_SUCCESS";
export const UPDATE_TASKID_ERROR = "UPDATE_TASKID_ERROR";

// update Status Pulang RJ
export const UPDATE_STATUSPULANGRJ = "UPDATE_STATUSPULANGRJ";
export const UPDATE_STATUSPULANGRJ_SUCCESS = "UPDATE_STATUSPULANGRJ_SUCCESS";
export const UPDATE_STATUSPULANGRJ_ERROR = "UPDATE_STATUSPULANGRJ_ERROR";

export const COMBO_HISTORY_UNIT_GET = "COMBO_HISTORY_UNIT_GET";
export const COMBO_HISTORY_UNIT_GET_SUCCESS = "COMBO_HISTORY_UNIT_GET_SUCCESS";
export const COMBO_HISTORY_UNIT_GET_ERROR = "COMBO_HISTORY_UNIT_GET_ERROR";

export const COMBO_TINDAKAN_GET = "COMBO_TINDAKAN_GET";
export const COMBO_TINDAKAN_GET_SUCCESS = "COMBO_TINDAKAN_GET_SUCCESS";
export const COMBO_TINDAKAN_GET_ERROR = "COMBO_TINDAKAN_GET_ERROR";