export const KENDALIDOKUMEN_RESET_FORM = "KENDALIDOKUMEN_RESET_FORM";

export const DAFTAR_DOKUMEN_REKAMMEDIS_GET = "DAFTAR_DOKUMEN_REKAMMEDIS_GET";
export const DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS = "DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS";
export const DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR = "DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR";

export const WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET = "WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET";
export const WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS = "WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS";
export const WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR = "WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR";

export const SAVE_DOKUMEN_REKAMMEDIS = "SAVE_DOKUMEN_REKAMMEDIS";
export const SAVE_DOKUMEN_REKAMMEDIS_SUCCESS = "SAVE_DOKUMEN_REKAMMEDIS_SUCCESS";
export const SAVE_DOKUMEN_REKAMMEDIS_ERROR = "SAVE_DOKUMEN_REKAMMEDIS_ERROR";

export const COMBO_LAPORAN_REKAMMEDIS_GET = "COMBO_LAPORAN_REKAMMEDIS_GET";
export const COMBO_LAPORAN_REKAMMEDIS_GET_SUCCESS = "COMBO_LAPORAN_REKAMMEDIS_GET_SUCCESS";
export const COMBO_LAPORAN_REKAMMEDIS_GET_ERROR = "COMBO_LAPORAN_REKAMMEDIS_GET_ERROR";

export const LIST_LAPORAN_PASIEN_DAFTAR_GET = "LIST_LAPORAN_PASIEN_DAFTAR_GET";
export const LIST_LAPORAN_PASIEN_DAFTAR_GET_SUCCESS = "LIST_LAPORAN_PASIEN_DAFTAR_GET_SUCCESS";
export const LIST_LAPORAN_PASIEN_DAFTAR_GET_ERROR = "LIST_LAPORAN_PASIEN_DAFTAR_GET_ERROR";

export const LIST_LAPORAN_PASIEN_BATAL_GET = "LIST_LAPORAN_PASIEN_BATAL_GET";
export const LIST_LAPORAN_PASIEN_BATAL_GET_SUCCESS = "LIST_LAPORAN_PASIEN_BATAL_GET_SUCCESS";
export const LIST_LAPORAN_PASIEN_BATAL_GET_ERROR = "LIST_LAPORAN_PASIEN_BATAL_GET_ERROR";

export const LIST_LAPORAN_PASIEN_KUNJUNGAN_GET = "LIST_LAPORAN_PASIEN_KUNJUNGAN_GET";
export const LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_SUCCESS = "LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_SUCCESS";
export const LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_ERROR = "LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_ERROR";

export const LAPORAN_RL_3_1_GET = "LAPORAN_RL_3_1_GET";
export const LAPORAN_RL_3_1_GET_SUCCESS = "LAPORAN_RL_3_1_GET_SUCCESS";
export const LAPORAN_RL_3_1_GET_ERROR = "LAPORAN_RL_3_1_GET_ERROR";

export const LAPORAN_RL_3_2_GET = "LAPORAN_RL_3_2_GET";
export const LAPORAN_RL_3_2_GET_SUCCESS = "LAPORAN_RL_3_2_GET_SUCCESS";
export const LAPORAN_RL_3_2_GET_ERROR = "LAPORAN_RL_3_2_GET_ERROR";

export const GET_DETAIL_JENIS_PRODUK = "KENDALI/GET_DETAIL_JENIS_PRODUK";
export const GET_DETAIL_JENIS_PRODUK_SUCCESS = "KENDALI/GET_DETAIL_JENIS_PRODUK_SUCCESS";
export const GET_DETAIL_JENIS_PRODUK_ERROR = "KENDALI/GET_DETAIL_JENIS_PRODUK_ERROR";

export const GET_LAYANAN_JENIS = "KENDALI/GET_LAYANAN_JENIS";
export const GET_LAYANAN_JENIS_SUCCESS = "KENDALI/GET_LAYANAN_JENIS_SUCCESS";
export const GET_LAYANAN_JENIS_ERROR = "KENDALI/GET_LAYANAN_JENIS_ERROR";

export const GET_MASTER_RL_FROM_INDUK = "KENDALI/GET_MASTER_RL_FROM_INDUK";
export const GET_MASTER_RL_FROM_INDUK_SUCCESS = "KENDALI/GET_MASTER_RL_FROM_INDUK_SUCCESS";
export const GET_MASTER_RL_FROM_INDUK_ERROR = "KENDALI/GET_MASTER_RL_FROM_INDUK_ERROR";

export const CREATE_OR_UPDATE_MAP_RL = "KENDALI/CREATE_OR_UPDATE_MAP_RL";
export const CREATE_OR_UPDATE_MAP_RL_SUCCESS = "KENDALI/CREATE_OR_UPDATE_MAP_RL_SUCCESS";
export const CREATE_OR_UPDATE_MAP_RL_ERROR = "KENDALI/CREATE_OR_UPDATE_MAP_RL_ERROR";

export const GET_LAYANAN_FROM_MASTER_RL = "KENDALI/GET_LAYANAN_FROM_MASTER_RL";
export const GET_LAYANAN_FROM_MASTER_RL_SUCCESS = "KENDALI/GET_LAYANAN_FROM_MASTER_RL_SUCCESS";
export const GET_LAYANAN_FROM_MASTER_RL_ERROR = "KENDALI/GET_LAYANAN_FROM_MASTER_RL_ERROR";

export const DELETE_MAP_RL = "KENDALI/DELETE_MAP_RL";
export const DELETE_MAP_RL_SUCCESS = "KENDALI/DELETE_MAP_RL_SUCCESS";
export const DELETE_MAP_RL_ERROR = "KENDALI/DELETE_MAP_RL_ERROR";

export const UPDATE_PRINTED = "KENDALI/UPDATE_PRINTED";
export const UPDATE_PRINTED_SUCCESS = "KENDALI/UPDATE_PRINTED_SUCCESS";
export const UPDATE_PRINTED_ERROR = "KENDALI/UPDATE_PRINTED_ERROR";

export const LAPORAN_RL_1_2_GET = "KENDALI/LAPORAN_RL_1_2_GET";
export const LAPORAN_RL_1_2_GET_SUCCESS = "KENDALI/LAPORAN_RL_1_2_GET_SUCCESS";
export const LAPORAN_RL_1_2_GET_ERROR = "KENDALI/LAPORAN_RL_1_2_GET_ERROR";

export const LAPORAN_RL_1_3_GET = "KENDALI/LAPORAN_RL_1_3_GET";
export const LAPORAN_RL_1_3_GET_SUCCESS = "KENDALI/LAPORAN_RL_1_3_GET_SUCCESS";
export const LAPORAN_RL_1_3_GET_ERROR = "KENDALI/LAPORAN_RL_1_3_GET_ERROR";

export const LAPORAN_RL_2_GET = "KENDALI/LAPORAN_RL_2_GET";
export const LAPORAN_RL_2_GET_SUCCESS = "KENDALI/LAPORAN_RL_2_GET_SUCCESS";
export const LAPORAN_RL_2_GET_ERROR = "KENDALI/LAPORAN_RL_2_GET_ERROR";

export const LAPORAN_RL_3_3_GET = "KENDALI/LAPORAN_RL_3_3_GET";
export const LAPORAN_RL_3_3_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_3_GET_SUCCESS";
export const LAPORAN_RL_3_3_GET_ERROR = "KENDALI/LAPORAN_RL_3_3_GET_ERROR";

export const LAPORAN_RL_3_4_GET = "KENDALI/LAPORAN_RL_3_4_GET";
export const LAPORAN_RL_3_4_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_4_GET_SUCCESS";
export const LAPORAN_RL_3_4_GET_ERROR = "KENDALI/LAPORAN_RL_3_4_GET_ERROR";

export const LAPORAN_RL_3_6_GET = "KENDALI/LAPORAN_RL_3_6_GET";
export const LAPORAN_RL_3_6_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_6_GET_SUCCESS";
export const LAPORAN_RL_3_6_GET_ERROR = "KENDALI/LAPORAN_RL_3_6_GET_ERROR";

export const LAPORAN_RL_3_7_GET = "KENDALI/LAPORAN_RL_3_7_GET";
export const LAPORAN_RL_3_7_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_7_GET_SUCCESS";
export const LAPORAN_RL_3_7_GET_ERROR = "KENDALI/LAPORAN_RL_3_7_GET_ERROR";

export const LAPORAN_RL_3_8_GET = "KENDALI/LAPORAN_RL_3_8_GET";
export const LAPORAN_RL_3_8_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_8_GET_SUCCESS";
export const LAPORAN_RL_3_8_GET_ERROR = "KENDALI/LAPORAN_RL_3_8_GET_ERROR";

export const LAPORAN_RL_3_14_GET = "KENDALI/LAPORAN_RL_3_14_GET";
export const LAPORAN_RL_3_14_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_14_GET_SUCCESS";
export const LAPORAN_RL_3_14_GET_ERROR = "KENDALI/LAPORAN_RL_3_14_GET_ERROR";

export const LAPORAN_RL_3_15_GET = "KENDALI/LAPORAN_RL_3_15_GET";
export const LAPORAN_RL_3_15_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_15_GET_SUCCESS";
export const LAPORAN_RL_3_15_GET_ERROR = "KENDALI/LAPORAN_RL_3_15_GET_ERROR";

export const LAPORAN_RL_3_11_GET = "KENDALI/LAPORAN_RL_3_11_GET";
export const LAPORAN_RL_3_11_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_11_GET_SUCCESS";
export const LAPORAN_RL_3_11_GET_ERROR = "KENDALI/LAPORAN_RL_3_11_GET_ERROR";

export const LAPORAN_RL_3_10_GET = "KENDALI/LAPORAN_RL_3_10_GET";
export const LAPORAN_RL_3_10_GET_SUCCESS = "KENDALI/LAPORAN_RL_3_10_GET_SUCCESS";
export const LAPORAN_RL_3_10_GET_ERROR = "KENDALI/LAPORAN_RL_3_10_GET_ERROR";

export const LAPORAN_RL_5_1_GET = "KENDALI/LAPORAN_RL_5_1_GET";
export const LAPORAN_RL_5_1_GET_SUCCESS = "KENDALI/LAPORAN_RL_5_1_GET_SUCCESS";
export const LAPORAN_RL_5_1_GET_ERROR = "KENDALI/LAPORAN_RL_5_1_GET_ERROR";

export const LAPORAN_RL_5_2_GET = "KENDALI/LAPORAN_RL_5_2_GET";
export const LAPORAN_RL_5_2_GET_SUCCESS = "KENDALI/LAPORAN_RL_5_2_GET_SUCCESS";
export const LAPORAN_RL_5_2_GET_ERROR = "KENDALI/LAPORAN_RL_5_2_GET_ERROR";

export const LAPORAN_RL_5_3_GET = "KENDALI/LAPORAN_RL_5_3_GET";
export const LAPORAN_RL_5_3_GET_SUCCESS = "KENDALI/LAPORAN_RL_5_3_GET_SUCCESS";
export const LAPORAN_RL_5_3_GET_ERROR = "KENDALI/LAPORAN_RL_5_3_GET_ERROR";

export const LAPORAN_RL_5_4_GET = "KENDALI/LAPORAN_RL_5_4_GET";
export const LAPORAN_RL_5_4_GET_SUCCESS = "KENDALI/LAPORAN_RL_5_4_GET_SUCCESS";
export const LAPORAN_RL_5_4_GET_ERROR = "KENDALI/LAPORAN_RL_5_4_GET_ERROR";