export const KENDALIDOKUMEN_RESET_FORM = "KENDALIDOKUMEN_RESET_FORM";

export const DAFTAR_DOKUMEN_REKAMMEDIS_GET = "DAFTAR_DOKUMEN_REKAMMEDIS_GET";
export const DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS = "DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS";
export const DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR = "DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR";

export const WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET = "WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET";
export const WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS = "WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_SUCCESS";
export const WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR = "WIDGET_DAFTAR_DOKUMEN_REKAMMEDIS_GET_ERROR";

export const SAVE_DOKUMEN_REKAMMEDIS = "SAVE_DOKUMEN_REKAMMEDIS";
export const SAVE_DOKUMEN_REKAMMEDIS_SUCCESS = "SAVE_DOKUMEN_REKAMMEDIS_SUCCESS";
export const SAVE_DOKUMEN_REKAMMEDIS_ERROR = "SAVE_DOKUMEN_REKAMMEDIS_ERROR";

export const COMBO_LAPORAN_REKAMMEDIS_GET = "COMBO_LAPORAN_REKAMMEDIS_GET";
export const COMBO_LAPORAN_REKAMMEDIS_GET_SUCCESS = "COMBO_LAPORAN_REKAMMEDIS_GET_SUCCESS";
export const COMBO_LAPORAN_REKAMMEDIS_GET_ERROR = "COMBO_LAPORAN_REKAMMEDIS_GET_ERROR";

export const LIST_LAPORAN_PASIEN_DAFTAR_GET = "LIST_LAPORAN_PASIEN_DAFTAR_GET";
export const LIST_LAPORAN_PASIEN_DAFTAR_GET_SUCCESS = "LIST_LAPORAN_PASIEN_DAFTAR_GET_SUCCESS";
export const LIST_LAPORAN_PASIEN_DAFTAR_GET_ERROR = "LIST_LAPORAN_PASIEN_DAFTAR_GET_ERROR";

export const LIST_LAPORAN_PASIEN_BATAL_GET = "LIST_LAPORAN_PASIEN_BATAL_GET";
export const LIST_LAPORAN_PASIEN_BATAL_GET_SUCCESS = "LIST_LAPORAN_PASIEN_BATAL_GET_SUCCESS";
export const LIST_LAPORAN_PASIEN_BATAL_GET_ERROR = "LIST_LAPORAN_PASIEN_BATAL_GET_ERROR";

export const LIST_LAPORAN_PASIEN_KUNJUNGAN_GET = "LIST_LAPORAN_PASIEN_KUNJUNGAN_GET";
export const LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_SUCCESS = "LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_SUCCESS";
export const LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_ERROR = "LIST_LAPORAN_PASIEN_KUNJUNGAN_GET_ERROR";

export const LAPORAN_RL_3_1_GET = "LAPORAN_RL_3_1_GET";
export const LAPORAN_RL_3_1_GET_SUCCESS = "LAPORAN_RL_3_1_GET_SUCCESS";
export const LAPORAN_RL_3_1_GET_ERROR = "LAPORAN_RL_3_1_GET_ERROR";