export const GET_LIST_INSTALASI = "STS/GET_LIST_INSTALASI";
export const GET_LIST_INSTALASI_SUCCESS = "STS/GET_LIST_INSTALASI_SUCCESS";
export const GET_LIST_INSTALASI_ERROR = "STS/GET_LIST_INSTALASI_ERROR";

export const UPSERT_ORGANIZATION_INSTALASI = "STS/UPSERT_ORGANIZATION_INSTALASI";
export const UPSERT_ORGANIZATION_INSTALASI_SUCCESS = "STS/UPSERT_ORGANIZATION_INSTALASI_SUCCESS";
export const UPSERT_ORGANIZATION_INSTALASI_ERROR = "STS/UPSERT_ORGANIZATION_INSTALASI_ERROR";

export const GET_LIST_UNIT = "STS/GET_LIST_UNIT";
export const GET_LIST_UNIT_SUCCESS = "STS/GET_LIST_UNIT_SUCCESS";
export const GET_LIST_UNIT_ERROR = "STS/GET_LIST_UNIT_ERROR";

export const UPSERT_LOCATION_UNIT = "STS/UPSERT_LOCATION_UNIT";
export const UPSERT_LOCATION_UNIT_SUCCESS = "STS/UPSERT_LOCATION_UNIT_SUCCESS";
export const UPSERT_LOCATION_UNIT_ERROR = "STS/UPSERT_LOCATION_UNIT_ERROR";

export const GET_LIST_PRACTITIONER = "STS/GET_LIST_PRACTITIONER";
export const GET_LIST_PRACTITIONER_SUCCESS = "STS/GET_LIST_PRACTITIONER_SUCCESS";
export const GET_LIST_PRACTITIONER_ERROR = "STS/GET_LIST_PRACTITIONER_ERROR";

export const UPSERT_PRACTITIONER = "STS/UPSERT_PRACTITIONER";
export const UPSERT_PRACTITIONER_SUCCESS = "STS/UPSERT_PRACTITIONER_SUCCESS";
export const UPSERT_PRACTITIONER_ERROR = "STS/UPSERT_PRACTITIONER_ERROR";