export const GET_LIST_INSTALASI = "STS/GET_LIST_INSTALASI";
export const GET_LIST_INSTALASI_SUCCESS = "STS/GET_LIST_INSTALASI_SUCCESS";
export const GET_LIST_INSTALASI_ERROR = "STS/GET_LIST_INSTALASI_ERROR";

export const UPSERT_ORGANIZATION_INSTALASI = "STS/UPSERT_ORGANIZATION_INSTALASI";
export const UPSERT_ORGANIZATION_INSTALASI_SUCCESS = "STS/UPSERT_ORGANIZATION_INSTALASI_SUCCESS";
export const UPSERT_ORGANIZATION_INSTALASI_ERROR = "STS/UPSERT_ORGANIZATION_INSTALASI_ERROR";