export const GET_LIST_INSTALASI = "STS/GET_LIST_INSTALASI";
export const GET_LIST_INSTALASI_SUCCESS = "STS/GET_LIST_INSTALASI_SUCCESS";
export const GET_LIST_INSTALASI_ERROR = "STS/GET_LIST_INSTALASI_ERROR";

export const UPSERT_ORGANIZATION_INSTALASI = "STS/UPSERT_ORGANIZATION_INSTALASI";
export const UPSERT_ORGANIZATION_INSTALASI_SUCCESS = "STS/UPSERT_ORGANIZATION_INSTALASI_SUCCESS";
export const UPSERT_ORGANIZATION_INSTALASI_ERROR = "STS/UPSERT_ORGANIZATION_INSTALASI_ERROR";

export const GET_LIST_UNIT = "STS/GET_LIST_UNIT";
export const GET_LIST_UNIT_SUCCESS = "STS/GET_LIST_UNIT_SUCCESS";
export const GET_LIST_UNIT_ERROR = "STS/GET_LIST_UNIT_ERROR";

export const UPSERT_LOCATION_UNIT = "STS/UPSERT_LOCATION_UNIT";
export const UPSERT_LOCATION_UNIT_SUCCESS = "STS/UPSERT_LOCATION_UNIT_SUCCESS";
export const UPSERT_LOCATION_UNIT_ERROR = "STS/UPSERT_LOCATION_UNIT_ERROR";

export const GET_LIST_PRACTITIONER = "STS/GET_LIST_PRACTITIONER";
export const GET_LIST_PRACTITIONER_SUCCESS = "STS/GET_LIST_PRACTITIONER_SUCCESS";
export const GET_LIST_PRACTITIONER_ERROR = "STS/GET_LIST_PRACTITIONER_ERROR";

export const UPSERT_PRACTITIONER = "STS/UPSERT_PRACTITIONER";
export const UPSERT_PRACTITIONER_SUCCESS = "STS/UPSERT_PRACTITIONER_SUCCESS";
export const UPSERT_PRACTITIONER_ERROR = "STS/UPSERT_PRACTITIONER_ERROR";

export const UPSERT_PATIENT = "STS/UPSERT_PATIENT";
export const UPSERT_PATIENT_SUCCESS = "STS/UPSERT_PATIENT_SUCCESS";
export const UPSERT_PATIENT_ERROR = "STS/UPSERT_PATIENT_ERROR";

export const UPSERT_ENCOUNTER = "STS/UPSERT_ENCOUNTER";
export const UPSERT_ENCOUNTER_SUCCESS = "STS/UPSERT_ENCOUNTER_SUCCESS";
export const UPSERT_ENCOUNTER_ERROR = "STS/UPSERT_ENCOUNTER_ERROR";

export const UPSERT_CONDITION = "STS/UPSERT_CONDITION";
export const UPSERT_CONDITION_SUCCESS = "STS/UPSERT_CONDITION_SUCCESS";
export const UPSERT_CONDITION_ERROR = "STS/UPSERT_CONDITION_ERROR";

export const UPSERT_ENCOUNTER_PULANG = "STS/UPSERT_ENCOUNTER_PULANG";
export const UPSERT_ENCOUNTER_PULANG_SUCCESS = "STS/UPSERT_ENCOUNTER_PULANG_SUCCESS";
export const UPSERT_ENCOUNTER_PULANG_ERROR = "STS/UPSERT_ENCOUNTER_PULANG_ERROR";

export const UPSERT_OBSERVATION = "STS/UPSERT_OBSERVATION";
export const UPSERT_OBSERVATION_SUCCESS = "STS/UPSERT_OBSERVATION_SUCCESS";
export const UPSERT_OBSERVATION_ERROR = "STS/UPSERT_OBSERVATION_ERROR";

export const GET_LIST_KAMAR = "STS/GET_LIST_KAMAR";
export const GET_LIST_KAMAR_SUCCESS = "STS/GET_LIST_KAMAR_SUCCESS";
export const GET_LIST_KAMAR_ERROR = "STS/GET_LIST_KAMAR_ERROR";

export const UPSERT_LOCATION_KAMAR = "STS/UPSERT_LOCATION_KAMAR";
export const UPSERT_LOCATION_KAMAR_SUCCESS = "STS/UPSERT_LOCATION_KAMAR_SUCCESS";
export const UPSERT_LOCATION_KAMAR_ERROR = "STS/UPSERT_LOCATION_KAMAR_ERROR";

export const GET_LIST_TEMPATTIDUR = "STS/GET_LIST_TEMPATTIDUR";
export const GET_LIST_TEMPATTIDUR_SUCCESS = "STS/GET_LIST_TEMPATTIDUR_SUCCESS";
export const GET_LIST_TEMPATTIDUR_ERROR = "STS/GET_LIST_TEMPATTIDUR_ERROR";

export const UPSERT_LOCATION_TEMPATTIDUR = "STS/UPSERT_LOCATION_TEMPATTIDUR";
export const UPSERT_LOCATION_TEMPATTIDUR_SUCCESS = "STS/UPSERT_LOCATION_TEMPATTIDUR_SUCCESS";
export const UPSERT_LOCATION_TEMPATTIDUR_ERROR = "STS/UPSERT_LOCATION_TEMPATTIDUR_ERROR";

export const UPSERT_PROCEDURE = "STS/UPSERT_PROCEDURE";
export const UPSERT_PROCEDURE_SUCCESS = "STS/UPSERT_PROCEDURE_SUCCESS";
export const UPSERT_PROCEDURE_ERROR = "STS/UPSERT_PROCEDURE_ERROR";

export const UPSERT_ALERGI = "STS/UPSERT_ALERGI";
export const UPSERT_ALERGI_SUCCESS = "STS/UPSERT_ALERGI_SUCCESS";
export const UPSERT_ALERGI_ERROR = "STS/UPSERT_ALERGI_ERROR";