export const SDM_RESET_FORM = "SDM_RESET_FORM";

export const GET_DAFTAR_PEGAWAI = "GET_DAFTAR_PEGAWAI";
export const GET_DAFTAR_PEGAWAI_SUCCESS = "GET_DAFTAR_PEGAWAI_SUCCESS";
export const GET_DAFTAR_PEGAWAI_ERROR = "GET_DAFTAR_PEGAWAI_ERROR";

export const GET_COMBO_SDM = "GET_COMBO_SDM";
export const GET_COMBO_SDM_SUCCESS = "GET_COMBO_SDM_SUCCESS";
export const GET_COMBO_SDM_ERROR = "GET_COMBO_SDM_ERROR";