export const SDM_RESET_FORM = "SDM_RESET_FORM";

export const GET_DAFTAR_PEGAWAI = "GET_DAFTAR_PEGAWAI";
export const GET_DAFTAR_PEGAWAI_SUCCESS = "GET_DAFTAR_PEGAWAI_SUCCESS";
export const GET_DAFTAR_PEGAWAI_ERROR = "GET_DAFTAR_PEGAWAI_ERROR";

export const GET_COMBO_SDM = "GET_COMBO_SDM";
export const GET_COMBO_SDM_SUCCESS = "GET_COMBO_SDM_SUCCESS";
export const GET_COMBO_SDM_ERROR = "GET_COMBO_SDM_ERROR";

export const SAVE_BIODATA_PEGAWAI = "SAVE_BIODATA_PEGAWAI";
export const SAVE_BIODATA_PEGAWAI_SUCCESS = "SAVE_BIODATA_PEGAWAI_SUCCESS";
export const SAVE_BIODATA_PEGAWAI_ERROR = "SAVE_BIODATA_PEGAWAI_ERROR";

export const GET_PEGAWAI_BYID = "GET_PEGAWAI_BYID";
export const GET_PEGAWAI_BYID_SUCCESS = "GET_PEGAWAI_BYID_SUCCESS";
export const GET_PEGAWAI_BYID_ERROR = "GET_PEGAWAI_BYID_ERROR";

export const GET_USER_ROLE_BYID_PEGAWAI = "GET_USER_ROLE_BYID_PEGAWAI";
export const GET_USER_ROLE_BYID_PEGAWAI_SUCCESS = "GET_USER_ROLE_BYID_PEGAWAI_SUCCESS";
export const GET_USER_ROLE_BYID_PEGAWAI_ERROR = "GET_USER_ROLE_BYID_PEGAWAI_ERROR";

export const SAVE_SIGNUP_USER_ROLE = "SAVE_SIGNUP_USER_ROLE";
export const SAVE_SIGNUP_USER_ROLE_SUCCESS = "SAVE_SIGNUP_USER_ROLE_SUCCESS";
export const SAVE_SIGNUP_USER_ROLE_ERROR = "SAVE_SIGNUP_USER_ROLE_ERROR";