export const SDM_RESET_FORM = "SDM_RESET_FORM";

export const GET_DAFTAR_PEGAWAI = "GET_DAFTAR_PEGAWAI";
export const GET_DAFTAR_PEGAWAI_SUCCESS = "GET_DAFTAR_PEGAWAI_SUCCESS";
export const GET_DAFTAR_PEGAWAI_ERROR = "GET_DAFTAR_PEGAWAI_ERROR";

export const GET_COMBO_SDM = "GET_COMBO_SDM";
export const GET_COMBO_SDM_SUCCESS = "GET_COMBO_SDM_SUCCESS";
export const GET_COMBO_SDM_ERROR = "GET_COMBO_SDM_ERROR";

export const SAVE_BIODATA_PEGAWAI = "SAVE_BIODATA_PEGAWAI";
export const SAVE_BIODATA_PEGAWAI_SUCCESS = "SAVE_BIODATA_PEGAWAI_SUCCESS";
export const SAVE_BIODATA_PEGAWAI_ERROR = "SAVE_BIODATA_PEGAWAI_ERROR";

export const GET_PEGAWAI_BYID = "GET_PEGAWAI_BYID";
export const GET_PEGAWAI_BYID_SUCCESS = "GET_PEGAWAI_BYID_SUCCESS";
export const GET_PEGAWAI_BYID_ERROR = "GET_PEGAWAI_BYID_ERROR";

export const GET_COMBO_JADWAL = "SDM/GET_COMBO_JADWAL";
export const GET_COMBO_JADWAL_SUCCESS = "SDM/GET_COMBO_JADWAL_SUCCESS";
export const GET_COMBO_JADWAL_ERROR = "SDM/GET_COMBO_JADWAL_ERROR";

export const GET_JADWAL_DOKTER_SDM = "SDM/GET_JADWAL_DOKTER_SDM";
export const GET_JADWAL_DOKTER_SDM_SUCCESS = "SDM/GET_JADWAL_DOKTER_SDM_SUCCESS";
export const GET_JADWAL_DOKTER_SDM_ERROR = "SDM/GET_JADWAL_DOKTER_SDM_ERROR";

export const UPSERT_JADWAL = "SDM/UPSERT_JADWAL";
export const UPSERT_JADWAL_SUCCESS = "SDM/UPSERT_JADWAL_SUCCESS";
export const UPSERT_JADWAL_ERROR = "SDM/UPSERT_JADWAL_ERROR";