


export const GET_PASIEN_RJ = "EIS/GET_PASIEN_RJ"
export const GET_PASIEN_RJ_SUCCESS = "EIS/GET_PASIEN_RJ_SUCCESS"
export const GET_PASIEN_RJ_ERROR = "EIS/GET_PASIEN_RJ_ERROR"

export const GET_PASIEN_IGD = "EIS/GET_PASIEN_IGD"
export const GET_PASIEN_IGD_SUCCESS = "EIS/GET_PASIEN_IGD_SUCCESS"
export const GET_PASIEN_IGD_ERROR = "EIS/GET_PASIEN_IGD_ERROR"

export const GET_PASIEN_RANAP = "EIS/GET_PASIEN_RANAP"
export const GET_PASIEN_RANAP_SUCCESS = "EIS/GET_PASIEN_RANAP_SUCCESS"
export const GET_PASIEN_RANAP_ERROR = "EIS/GET_PASIEN_RANAP_ERROR"

export const GET_COUNT_CARA_BAYAR = "EIS/GET_COUNT_CARA_BAYAR"
export const GET_COUNT_CARA_BAYAR_SUCCESS = "EIS/GET_COUNT_CARA_BAYAR_SUCCESS"
export const GET_COUNT_CARA_BAYAR_ERROR = "EIS/GET_COUNT_CARA_BAYAR_ERROR"

export const GET_POLIKLINIK_TERBANYAK = "EIS/GET_POLIKLINIK_TERBANYAK"
export const GET_POLIKLINIK_TERBANYAK_SUCCESS = "EIS/GET_POLIKLINIK_TERBANYAK_SUCCESS"
export const GET_POLIKLINIK_TERBANYAK_ERROR = "EIS/GET_POLIKLINIK_TERBANYAK_ERROR"

export const GET_COUNT_UNIT = "EIS/GET_COUNT_UNIT"
export const GET_COUNT_UNIT_SUCCESS = "EIS/GET_COUNT_UNIT_SUCCESS"
export const GET_COUNT_UNIT_ERROR = "EIS/GET_COUNT_UNIT_ERROR"

export const GET_STATUS_PEGAWAI = "EIS/GET_STATUS_PEGAWAI"
export const GET_STATUS_PEGAWAI_SUCCESS = "EIS/GET_STATUS_PEGAWAI_SUCCESS"
export const GET_STATUS_PEGAWAI_ERROR = "EIS/GET_STATUS_PEGAWAI_ERROR"

export const GET_PEGAWAI_PENSIUN = "EIS/GET_PEGAWAI_PENSIUN"
export const GET_PEGAWAI_PENSIUN_SUCCESS = "EIS/GET_PEGAWAI_PENSIUN_SUCCESS"
export const GET_PEGAWAI_PENSIUN_ERROR = "EIS/GET_PEGAWAI_PENSIUN_ERROR"
