export const RADIOLOGI_RESET_FORM = "RADIOLOGI_RESET_FORM";

export const SAVE_ORDER_PELAYANAN_RADIOLOGI = "SAVE_ORDER_PELAYANAN_RADIOLOGI";
export const SAVE_ORDER_PELAYANAN_RADIOLOGI_SUCCESS = "SAVE_ORDER_PELAYANAN_RADIOLOGI_SUCCESS";
export const SAVE_ORDER_PELAYANAN_RADIOLOGI_ERROR = "SAVE_ORDER_PELAYANAN_RADIOLOGI_ERROR";

export const DAFTAR_ORDER_RADIOLOGI_GET = "DAFTAR_ORDER_RADIOLOGI_GET";
export const DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS = "DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS";
export const DAFTAR_ORDER_RADIOLOGI_GET_ERROR = "DAFTAR_ORDER_RADIOLOGI_GET_ERROR";

export const WIDGET_DAFTAR_ORDER_RADIOLOGI_GET = "WIDGET_DAFTAR_ORDER_RADIOLOGI_GET";
export const WIDGET_DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS = "WIDGET_DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS";
export const WIDGET_DAFTAR_ORDER_RADIOLOGI_GET_ERROR = "WIDGET_DAFTAR_ORDER_RADIOLOGI_GET_ERROR";

export const LIST_DAFTAR_ORDER_RADIOLOGI_GET = "LIST_DAFTAR_ORDER_RADIOLOGI_GET";
export const LIST_DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS = "LIST_DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS";
export const LIST_DAFTAR_ORDER_RADIOLOGI_GET_ERROR = "LIST_DAFTAR_ORDER_RADIOLOGI_GET_ERROR";

export const LIST_ORDER_BY_NOREC_GET = "LIST_ORDER_BY_NOREC_GET";
export const LIST_ORDER_BY_NOREC_GET_SUCCESS = "LIST_ORDER_BY_NOREC_GET_SUCCESS";
export const LIST_ORDER_BY_NOREC_GET_ERROR = "LIST_ORDER_BY_NOREC_GET_ERROR";

export const LIST_KAMAR_RADIOLOGI_GET = "LIST_KAMAR_RADIOLOGI_GET";
export const LIST_KAMAR_RADIOLOGI_GET_SUCCESS = "LIST_KAMAR_RADIOLOGI_GET_SUCCESS";
export const LIST_KAMAR_RADIOLOGI_GET_ERROR = "LIST_KAMAR_RADIOLOGI_GET_ERROR";

export const UPDATE_TGLRENCANA_RADIOLOGI = "UPDATE_TGLRENCANA_RADIOLOGI";
export const UPDATE_TGLRENCANA_RADIOLOGI_SUCCESS = "UPDATE_TGLRENCANA_RADIOLOGI_SUCCESS";
export const UPDATE_TGLRENCANA_RADIOLOGI_ERROR = "UPDATE_TGLRENCANA_RADIOLOGI_ERROR";

export const SAVE_VERIFIKASI_RADIOLOGI = "SAVE_VERIFIKASI_RADIOLOGI";
export const SAVE_VERIFIKASI_RADIOLOGI_SUCCESS = "SAVE_VERIFIKASI_RADIOLOGI_SUCCESS";
export const SAVE_VERIFIKASI_RADIOLOGI_ERROR = "SAVE_VERIFIKASI_RADIOLOGI_ERROR";

export const DELETE_ORDER_PELAYANAN = "DELETE_ORDER_PELAYANAN";
export const DELETE_ORDER_PELAYANAN_SUCCESS = "DELETE_ORDER_PELAYANAN_SUCCESS";
export const DELETE_ORDER_PELAYANAN_ERROR = "DELETE_ORDER_PELAYANAN_ERROR";

export const DELETE_DETAIL_ORDER_PELAYANAN = "DELETE_DETAIL_ORDER_PELAYANAN";
export const DELETE_DETAIL_ORDER_PELAYANAN_SUCCESS = "DELETE_DETAIL_ORDER_PELAYANAN_SUCCESS";
export const DELETE_DETAIL_ORDER_PELAYANAN_ERROR = "DELETE_DETAIL_ORDER_PELAYANAN_ERROR";