export const RADIOLOGI_RESET_FORM = "RADIOLOGI_RESET_FORM";

export const SAVE_ORDER_PELAYANAN_RADIOLOGI = "SAVE_ORDER_PELAYANAN_RADIOLOGI";
export const SAVE_ORDER_PELAYANAN_RADIOLOGI_SUCCESS = "SAVE_ORDER_PELAYANAN_RADIOLOGI_SUCCESS";
export const SAVE_ORDER_PELAYANAN_RADIOLOGI_ERROR = "SAVE_ORDER_PELAYANAN_RADIOLOGI_ERROR";

export const DAFTAR_ORDER_RADIOLOGI_GET = "DAFTAR_ORDER_RADIOLOGI_GET";
export const DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS = "DAFTAR_ORDER_RADIOLOGI_GET_SUCCESS";
export const DAFTAR_ORDER_RADIOLOGI_GET_ERROR = "DAFTAR_ORDER_RADIOLOGI_GET_ERROR";