
export const PELAYANAN_FROM_ANTREAN_GET = 'PELAYANAN_FROM_ANTREAN_GET';
export const PELAYANAN_FROM_ANTREAN_GET_SUCCESS = 'PELAYANAN_FROM_ANTREAN_GET_SUCCESS';
export const PELAYANAN_FROM_ANTREAN_GET_ERROR = 'PELAYANAN_FROM_ANTREAN_GET_ERROR';
export const PELAYANAN_FROM_ANTREAN_GET_RESET = 'PELAYANAN_FROM_ANTREAN_GET_RESET';

export const NOTA_VERIF_CREATE = 'NOTA_VERIF_CREATE';
export const NOTA_VERIF_CREATE_SUCCESS = 'NOTA_VERIF_CREATE_SUCCESS';
export const NOTA_VERIF_CREATE_ERROR = 'NOTA_VERIF_CREATE_ERROR';
export const NOTA_VERIF_CREATE_RESET = 'NOTA_VERIF_CREATE_RESET';

export const DAFTAR_TAGIHAN_PASIEN_GET = 'DAFTAR_TAGIHAN_PASIEN_GET';
export const DAFTAR_TAGIHAN_PASIEN_GET_SUCCESS = 'DAFTAR_TAGIHAN_PASIEN_GET_SUCCESS';
export const DAFTAR_TAGIHAN_PASIEN_GET_ERROR = 'DAFTAR_TAGIHAN_PASIEN_GET_ERROR';
export const DAFTAR_TAGIHAN_PASIEN_GET_RESET = 'DAFTAR_TAGIHAN_PASIEN_GET_RESET';

export const PELAYANAN_FROM_VERIF_GET = 'PELAYANAN_FROM_VERIF_GET';
export const PELAYANAN_FROM_VERIF_GET_SUCCESS = 'PELAYANAN_FROM_VERIF_GET_SUCCESS';
export const PELAYANAN_FROM_VERIF_GET_ERROR = 'PELAYANAN_FROM_VERIF_GET_ERROR';
export const PELAYANAN_FROM_VERIF_GET_RESET = 'PELAYANAN_FROM_VERIF_GET_RESET';

export const BUKTI_BAYAR_CREATE = 'BUKTI_BAYAR_CREATE';
export const BUKTI_BAYAR_CREATE_SUCCESS = 'BUKTI_BAYAR_CREATE_SUCCESS';
export const BUKTI_BAYAR_CREATE_ERROR = 'BUKTI_BAYAR_CREATE_ERROR';
export const BUKTI_BAYAR_CREATE_RESET = 'BUKTI_BAYAR_CREATE_RESET';

export const VERIF_NOTA_CANCEL = 'VERIF_NOTA_CANCEL';
export const VERIF_NOTA_CANCEL_SUCCESS = 'VERIF_NOTA_CANCEL_SUCCESS';
export const VERIF_NOTA_CANCEL_ERROR = 'VERIF_NOTA_CANCEL_ERROR';
export const VERIF_NOTA_CANCEL_RESET = 'VERIF_NOTA_CANCEL_RESET';

export const BUKTI_BAYAR_CANCEL = 'BUKTI_BAYAR_CANCEL';
export const BUKTI_BAYAR_CANCEL_SUCCESS = 'BUKTI_BAYAR_CANCEL_SUCCESS';
export const BUKTI_BAYAR_CANCEL_ERROR = 'BUKTI_BAYAR_CANCEL_ERROR';
export const BUKTI_BAYAR_CANCEL_RESET = 'BUKTI_BAYAR_CANCEL_RESET';

export const DAFTAR_PIUTANG_PASIEN_GET = 'DAFTAR_PIUTANG_PASIEN_GET';
export const DAFTAR_PIUTANG_PASIEN_GET_SUCCESS = 'DAFTAR_PIUTANG_PASIEN_GET_SUCCESS';
export const DAFTAR_PIUTANG_PASIEN_GET_ERROR = 'DAFTAR_PIUTANG_PASIEN_GET_ERROR';
export const DAFTAR_PIUTANG_PASIEN_GET_RESET = 'DAFTAR_PIUTANG_PASIEN_GET_RESET';