
export const PELAYANAN_FROM_DP_GET = 'PELAYANAN_FROM_DP_GET';
export const PELAYANAN_FROM_DP_GET_SUCCESS = 'PELAYANAN_FROM_DP_GET_SUCCESS';
export const PELAYANAN_FROM_DP_GET_ERROR = 'PELAYANAN_FROM_DP_GET_ERROR';
export const PELAYANAN_FROM_DP_GET_RESET = 'PELAYANAN_FROM_DP_GET_RESET';

export const NOTA_VERIF_CREATE = 'NOTA_VERIF_CREATE';
export const NOTA_VERIF_CREATE_SUCCESS = 'NOTA_VERIF_CREATE_SUCCESS';
export const NOTA_VERIF_CREATE_ERROR = 'NOTA_VERIF_CREATE_ERROR';
export const NOTA_VERIF_CREATE_RESET = 'NOTA_VERIF_CREATE_RESET';

export const DAFTAR_TAGIHAN_PASIEN_GET = 'DAFTAR_TAGIHAN_PASIEN_GET';
export const DAFTAR_TAGIHAN_PASIEN_GET_SUCCESS = 'DAFTAR_TAGIHAN_PASIEN_GET_SUCCESS';
export const DAFTAR_TAGIHAN_PASIEN_GET_ERROR = 'DAFTAR_TAGIHAN_PASIEN_GET_ERROR';
export const DAFTAR_TAGIHAN_PASIEN_GET_RESET = 'DAFTAR_TAGIHAN_PASIEN_GET_RESET';

export const PELAYANAN_FROM_VERIF_GET = 'PELAYANAN_FROM_VERIF_GET';
export const PELAYANAN_FROM_VERIF_GET_SUCCESS = 'PELAYANAN_FROM_VERIF_GET_SUCCESS';
export const PELAYANAN_FROM_VERIF_GET_ERROR = 'PELAYANAN_FROM_VERIF_GET_ERROR';
export const PELAYANAN_FROM_VERIF_GET_RESET = 'PELAYANAN_FROM_VERIF_GET_RESET';

export const BUKTI_BAYAR_CREATE = 'BUKTI_BAYAR_CREATE';
export const BUKTI_BAYAR_CREATE_SUCCESS = 'BUKTI_BAYAR_CREATE_SUCCESS';
export const BUKTI_BAYAR_CREATE_ERROR = 'BUKTI_BAYAR_CREATE_ERROR';
export const BUKTI_BAYAR_CREATE_RESET = 'BUKTI_BAYAR_CREATE_RESET';

export const VERIF_NOTA_CANCEL = 'VERIF_NOTA_CANCEL';
export const VERIF_NOTA_CANCEL_SUCCESS = 'VERIF_NOTA_CANCEL_SUCCESS';
export const VERIF_NOTA_CANCEL_ERROR = 'VERIF_NOTA_CANCEL_ERROR';
export const VERIF_NOTA_CANCEL_RESET = 'VERIF_NOTA_CANCEL_RESET';

export const BUKTI_BAYAR_CANCEL = 'BUKTI_BAYAR_CANCEL';
export const BUKTI_BAYAR_CANCEL_SUCCESS = 'BUKTI_BAYAR_CANCEL_SUCCESS';
export const BUKTI_BAYAR_CANCEL_ERROR = 'BUKTI_BAYAR_CANCEL_ERROR';
export const BUKTI_BAYAR_CANCEL_RESET = 'BUKTI_BAYAR_CANCEL_RESET';

export const DAFTAR_PIUTANG_PASIEN_GET = 'DAFTAR_PIUTANG_PASIEN_GET';
export const DAFTAR_PIUTANG_PASIEN_GET_SUCCESS = 'DAFTAR_PIUTANG_PASIEN_GET_SUCCESS';
export const DAFTAR_PIUTANG_PASIEN_GET_ERROR = 'DAFTAR_PIUTANG_PASIEN_GET_ERROR';
export const DAFTAR_PIUTANG_PASIEN_GET_RESET = 'DAFTAR_PIUTANG_PASIEN_GET_RESET';

export const PAYMENT_PIUTANG_PASIEN_GET = 'PAYMENT_PIUTANG_PASIEN_GET';
export const PAYMENT_PIUTANG_PASIEN_GET_SUCCESS = 'PAYMENT_PIUTANG_PASIEN_GET_SUCCESS';
export const PAYMENT_PIUTANG_PASIEN_GET_ERROR = 'PAYMENT_PIUTANG_PASIEN_GET_ERROR';
export const PAYMENT_PIUTANG_PASIEN_GET_RESET = 'PAYMENT_PIUTANG_PASIEN_GET_RESET';

export const LAPORAN_PENDAPATAN_KASIR_GET = 'LAPORAN_PENDAPATAN_KASIR_GET';
export const LAPORAN_PENDAPATAN_KASIR_GET_SUCCESS = 'LAPORAN_PENDAPATAN_KASIR_GET_SUCCESS';
export const LAPORAN_PENDAPATAN_KASIR_GET_ERROR = 'LAPORAN_PENDAPATAN_KASIR_GET_ERROR';
export const LAPORAN_PENDAPATAN_KASIR_GET_RESET = 'LAPORAN_PENDAPATAN_KASIR_GET_RESET';

export const GET_PIUTANG_AFTER_DATE = "PAYMENT/GET_PIUTANG_AFTER_DATE";
export const GET_PIUTANG_AFTER_DATE_SUCCESS = "PAYMENT/GET_PIUTANG_AFTER_DATE_SUCCESS";
export const GET_PIUTANG_AFTER_DATE_ERROR = "PAYMENT/GET_PIUTANG_AFTER_DATE_ERROR";

export const GET_DAFTAR_VERIFIKASI_REMUNERASI = "PAYMENT/GET_DAFTAR_VERIFIKASI_REMUNERASI";
export const GET_DAFTAR_VERIFIKASI_REMUNERASI_SUCCESS = "PAYMENT/GET_DAFTAR_VERIFIKASI_REMUNERASI_SUCCESS";
export const GET_DAFTAR_VERIFIKASI_REMUNERASI_ERROR = "PAYMENT/GET_DAFTAR_VERIFIKASI_REMUNERASI_ERROR";

export const UPSERT_VERIFIKASI_REMUNERASI = "PAYMENT/UPSERT_VERIFIKASI_REMUNERASI";
export const UPSERT_VERIFIKASI_REMUNERASI_SUCCESS = "PAYMENT/UPSERT_VERIFIKASI_REMUNERASI_SUCCESS";
export const UPSERT_VERIFIKASI_REMUNERASI_ERROR = "PAYMENT/UPSERT_VERIFIKASI_REMUNERASI_ERROR";
export const UPSERT_VERIFIKASI_REMUNERASI_RESET = 'PAYMENT/UPSERT_VERIFIKASI_REMUNERASI_RESET';

export const GET_DAFTAR_SUDAH_VERIFIKASI_REMUNERASI = "PAYMENT/GET_DAFTAR_SUDAH_VERIFIKASI_REMUNERASI";
export const GET_DAFTAR_SUDAH_VERIFIKASI_REMUNERASI_SUCCESS = "PAYMENT/GET_DAFTAR_SUDAH_VERIFIKASI_REMUNERASI_SUCCESS";
export const GET_DAFTAR_SUDAH_VERIFIKASI_REMUNERASI_ERROR = "PAYMENT/GET_DAFTAR_SUDAH_VERIFIKASI_REMUNERASI_ERROR";

export const GET_COMBO_SETOR = "PAYMENT/GET_COMBO_SETOR"
export const GET_COMBO_SETOR_SUCCESS = "PAYMENT/GET_COMBO_SETOR_SUCCESS"
export const GET_COMBO_SETOR_ERROR = "PAYMENT/GET_COMBO_SETOR_ERROR"

export const GET_PEMBAYARAN_SETOR = "PAYMENT/GET_PEMBAYARAN_SETOR"
export const GET_PEMBAYARAN_SETOR_SUCCESS = "PAYMENT/GET_PEMBAYARAN_SETOR_SUCCESS"
export const GET_PEMBAYARAN_SETOR_ERROR = "PAYMENT/GET_PEMBAYARAN_SETOR_ERROR"

