
export const PELAYANAN_FROM_ANTREAN_GET = 'PELAYANAN_FROM_ANTREAN_GET';
export const PELAYANAN_FROM_ANTREAN_GET_SUCCESS = 'PELAYANAN_FROM_ANTREAN_GET_SUCCESS';
export const PELAYANAN_FROM_ANTREAN_GET_ERROR = 'PELAYANAN_FROM_ANTREAN_GET_ERROR';
export const PELAYANAN_FROM_ANTREAN_GET_RESET = 'PELAYANAN_FROM_ANTREAN_GET_RESET';

export const NOTA_VERIF_CREATE = 'NOTA_VERIF_CREATE';
export const NOTA_VERIF_CREATE_SUCCESS = 'NOTA_VERIF_CREATE_SUCCESS';
export const NOTA_VERIF_CREATE_ERROR = 'NOTA_VERIF_CREATE_ERROR';
export const NOTA_VERIF_CREATE_RESET = 'NOTA_VERIF_CREATE_RESET';
