export const BEDAH_SENTRAL_RESET_FORM = "BEDAH_SENTRAL_RESET_FORM";

export const WIDGET_ORDER_OPERASI_GET = "WIDGET_ORDER_OPERASI_GET";
export const WIDGET_ORDER_OPERASI_GET_SUCCESS = "WIDGET_ORDER_OPERASI_GET_SUCCESS";
export const WIDGET_ORDER_OPERASI_GET_ERROR = "WIDGET_ORDER_OPERASI_GET_ERROR";

export const GET_DAFTAR_ORDER_OPERASI = "GET_DAFTAR_ORDER_OPERASI";
export const GET_DAFTAR_ORDER_OPERASI_SUCCESS = "GET_DAFTAR_ORDER_OPERASI_SUCCESS";
export const GET_DAFTAR_ORDER_OPERASI_ERROR = "GET_DAFTAR_ORDER_OPERASI_ERROR";

export const GET_COMBO_ORDER_OPERASI = "GET_COMBO_ORDER_OPERASI";
export const GET_COMBO_ORDER_OPERASI_SUCCESS = "GET_COMBO_ORDER_OPERASI_SUCCESS";
export const GET_COMBO_ORDER_OPERASI_ERROR = "GET_COMBO_ORDER_OPERASI_ERROR";

export const UPDATE_ORDER_OPERASI = "UPDATE_ORDER_OPERASI";
export const UPDATE_ORDER_OPERASI_SUCCESS = "UPDATE_ORDER_OPERASI_SUCCESS";
export const UPDATE_ORDER_OPERASI_ERROR = "UPDATE_ORDER_OPERASI_ERROR";

export const GET_DAFTAR_PASIEN_OPERASI = "GET_DAFTAR_PASIEN_OPERASI";
export const GET_DAFTAR_PASIEN_OPERASI_SUCCESS = "GET_DAFTAR_PASIEN_OPERASI_SUCCESS";
export const GET_DAFTAR_PASIEN_OPERASI_ERROR = "GET_DAFTAR_PASIEN_OPERASI_ERROR";