export const BEDAH_SENTRAL_RESET_FORM = "BEDAH_SENTRAL_RESET_FORM";

export const WIDGET_ORDER_OPERASI_GET = "WIDGET_ORDER_OPERASI_GET";
export const WIDGET_ORDER_OPERASI_GET_SUCCESS = "WIDGET_ORDER_OPERASI_GET_SUCCESS";
export const WIDGET_ORDER_OPERASI_GET_ERROR = "WIDGET_ORDER_OPERASI_GET_ERROR";