


export const GET_JADWAL_DOKTER = "DAFTAR_PASIEN_LAMA/GET_JADWAL_DOKTER"
export const GET_JADWAL_DOKTER_SUCCESS = "DAFTAR_PASIEN_LAMA/GET_JADWAL_DOKTER_SUCCESS"
export const GET_JADWAL_DOKTER_ERROR = "DAFTAR_PASIEN_LAMA/GET_JADWAL_DOKTER_ERROR"
