


export const GET_JADWAL_DOKTER = "DAFTAR_PASIEN_LAMA/GET_JADWAL_DOKTER"
export const GET_JADWAL_DOKTER_SUCCESS = "DAFTAR_PASIEN_LAMA/GET_JADWAL_DOKTER_SUCCESS"
export const GET_JADWAL_DOKTER_ERROR = "DAFTAR_PASIEN_LAMA/GET_JADWAL_DOKTER_ERROR"

export const GET_PASIEN_LAMA = "DAFTAR_PASIEN_LAMA/GET_PASIEN_LAMA"
export const GET_PASIEN_LAMA_SUCCESS = "DAFTAR_PASIEN_LAMA/GET_PASIEN_LAMA_SUCCESS"
export const GET_PASIEN_LAMA_ERROR = "DAFTAR_PASIEN_LAMA/GET_PASIEN_LAMA_ERROR"

export const GET_DOKTER_PASIEN = "DAFTAR_PASIEN_LAMA/GET_DOKTER_PASIEN"
export const GET_DOKTER_PASIEN_SUCCESS = "DAFTAR_PASIEN_LAMA/GET_DOKTER_PASIEN_SUCCESS"
export const GET_DOKTER_PASIEN_ERROR = "DAFTAR_PASIEN_LAMA/GET_DOKTER_PASIEN_ERROR"

export const GET_COMBO_DAFTAR = "DAFTAR_PASIEN_LAMA/GET_COMBO_DAFTAR"
export const GET_COMBO_DAFTAR_SUCCESS = "DAFTAR_PASIEN_LAMA/GET_COMBO_DAFTAR_SUCCESS"
export const GET_COMBO_DAFTAR_ERROR = "DAFTAR_PASIEN_LAMA/GET_COMBO_DAFTAR_ERROR"