export const GET_LOKET_SISA = "VIEWER/GET_LOKET_SISA";
export const GET_LOKET_SISA_SUCCESS = "VIEWER/GET_LOKET_SISA_SUCCESS";
export const GET_LOKET_SISA_ERROR = "VIEWER/GET_LOKET_SISA_ERROR";

export const PANGGIL_LOKET = "VIEWER/PANGGIL_LOKET";
export const PANGGIL_LOKET_SUCCESS = "VIEWER/PANGGIL_LOKET_SUCCESS";
export const PANGGIL_LOKET_ERROR = "VIEWER/PANGGIL_LOKET_ERROR";

export const GET_ALL_LOKET = "VIEWER/GET_ALL_LOKET";
export const GET_ALL_LOKET_SUCCESS = "VIEWER/GET_ALL_LOKET_SUCCESS";
export const GET_ALL_LOKET_ERROR = "VIEWER/GET_ALL_LOKET_ERROR";

export const GET_ALL_TERPANGGIL = "VIEWER/GET_ALL_TERPANGGIL";
export const GET_ALL_TERPANGGIL_SUCCESS = "VIEWER/GET_ALL_TERPANGGIL_SUCCESS";
export const GET_ALL_TERPANGGIL_ERROR = "VIEWER/GET_ALL_TERPANGGIL_ERROR";

export const PANGGIL_ULANG_ANTREAN = "VIEWER/PANGGIL_ULANG_ANTREAN";
export const PANGGIL_ULANG_ANTREAN_SUCCESS = "VIEWER/PANGGIL_ULANG_ANTREAN_SUCCESS";
export const PANGGIL_ULANG_ANTREAN_ERROR = "VIEWER/PANGGIL_ULANG_ANTREAN_ERROR";

export const GET_JADWAL_DOKTER = "VIEWER/GET_JADWAL_DOKTER";
export const GET_JADWAL_DOKTER_SUCCESS = "VIEWER/GET_JADWAL_DOKTER_SUCCESS";
export const GET_JADWAL_DOKTER_ERROR = "VIEWER/GET_JADWAL_DOKTER_ERROR";

export const GET_JADWAL_OPERASI = "VIEWER/GET_JADWAL_OPERASI";
export const GET_JADWAL_OPERASI_SUCCESS = "VIEWER/GET_JADWAL_OPERASI_SUCCESS";
export const GET_JADWAL_OPERASI_ERROR = "VIEWER/GET_JADWAL_OPERASI_ERROR";