export const GET_LOKET_SISA = "VIEWER/GET_LOKET_SISA";
export const GET_LOKET_SISA_SUCCESS = "VIEWER/GET_LOKET_SISA_SUCCESS";
export const GET_LOKET_SISA_ERROR = "VIEWER/GET_LOKET_SISA_ERROR";

export const PANGGIL_LOKET = "VIEWER/PANGGIL_LOKET";
export const PANGGIL_LOKET_SUCCESS = "VIEWER/PANGGIL_LOKET_SUCCESS";
export const PANGGIL_LOKET_ERROR = "VIEWER/PANGGIL_LOKET_ERROR";

export const GET_ALL_LOKET = "VIEWER/GET_ALL_LOKET";
export const GET_ALL_LOKET_SUCCESS = "VIEWER/GET_ALL_LOKET_SUCCESS";
export const GET_ALL_LOKET_ERROR = "VIEWER/GET_ALL_LOKET_ERROR";