export const GET_TEMPAT_TIDUR = "TT/GET_TEMPAT_TIDUR";
export const GET_TEMPAT_TIDUR_SUCCESS = "TT/GET_TEMPAT_TIDUR_SUCCESS";
export const GET_TEMPAT_TIDUR_ERROR = "TT/GET_TEMPAT_TIDUR_ERROR";

export const GET_UNIT_TEMPAT_TIDUR = "TT/GET_UNIT_TEMPAT_TIDUR";
export const GET_UNIT_TEMPAT_TIDUR_SUCCESS = "TT/GET_UNIT_TEMPAT_TIDUR_SUCCESS";
export const GET_UNIT_TEMPAT_TIDUR_ERROR = "TT/GET_UNIT_TEMPAT_TIDUR_ERROR";

export const GET_COMBO_TEMPAT_TIDUR = "TT/GET_COMBO_TEMPAT_TIDUR";
export const GET_COMBO_TEMPAT_TIDUR_SUCCESS = "TT/GET_COMBO_TEMPAT_TIDUR_SUCCESS";
export const GET_COMBO_TEMPAT_TIDUR_ERROR = "TT/GET_COMBO_TEMPAT_TIDUR_ERROR";

export const UPSERT_TEMPAT_TIDUR = "TT/UPSERT_TEMPAT_TIDUR";
export const UPSERT_TEMPAT_TIDUR_SUCCESS = "TT/UPSERT_TEMPAT_TIDUR_SUCCESS";
export const UPSERT_TEMPAT_TIDUR_ERROR = "TT/UPSERT_TEMPAT_TIDUR_ERROR";