
export const GET_COMBO_VERIFIKASI_ONLINE = "DAFTARPASIENONLINE/GET_COMBO_VERIFIKASI_ONLINE";
export const GET_COMBO_VERIFIKASI_ONLINE_SUCCESS = "DAFTARPASIENONLINE/GET_COMBO_VERIFIKASI_ONLINE_SUCCESS";
export const GET_COMBO_VERIFIKASI_ONLINE_ERROR = "DAFTARPASIENONLINE/GET_COMBO_VERIFIKASI_ONLINE_ERROR";

export const GET_DAFTAR_PASIEN_ONLINE = "DAFTARPASIENONLINE/GET_DAFTAR_PASIEN_ONLINE";
export const GET_DAFTAR_PASIEN_ONLINE_SUCCESS = "DAFTARPASIENONLINE/GET_DAFTAR_PASIEN_ONLINE_SUCCESS";
export const GET_DAFTAR_PASIEN_ONLINE_ERROR = "DAFTARPASIENONLINE/GET_DAFTAR_PASIEN_ONLINE_ERROR";