



export const GET_TOTAL_HARGA_PRODUK = "MTT/GET_TOTAL_HARGA_PRODUK"
export const GET_TOTAL_HARGA_PRODUK_SUCCESS = "MTT/GET_TOTAL_HARGA_PRODUK_SUCCESS"
export const GET_TOTAL_HARGA_PRODUK_ERROR = "MTT/GET_TOTAL_HARGA_PRODUK_ERROR"

export const GET_COMBO_TARIF_TINDAKAN = "MTT/GET_COMBO_TARIF_TINDAKAN"
export const GET_COMBO_TARIF_TINDAKAN_SUCCESS = "MTT/GET_COMBO_TARIF_TINDAKAN_SUCCESS"
export const GET_COMBO_TARIF_TINDAKAN_ERROR = "MTT/GET_COMBO_TARIF_TINDAKAN_ERROR"

export const UPSERT_TARIF_TINDAKAN = "MTT/UPSERT_TARIF_TINDAKAN"
export const UPSERT_TARIF_TINDAKAN_SUCCESS = "MTT/UPSERT_TARIF_TINDAKAN_SUCCESS"
export const UPSERT_TARIF_TINDAKAN_ERROR = "MTT/UPSERT_TARIF_TINDAKAN_ERROR"

export const GET_TOTAL_TARIF = "MTT/GET_TOTAL_TARIF"
export const GET_TOTAL_TARIF_SUCCESS = "MTT/GET_TOTAL_TARIF_SUCCESS"
export const GET_TOTAL_TARIF_ERROR = "MTT/GET_TOTAL_TARIF_ERROR"

