



export const GET_TOTAL_HARGA_PRODUK = "MTT/GET_TOTAL_HARGA_PRODUK"
export const GET_TOTAL_HARGA_PRODUK_SUCCESS = "MTT/GET_TOTAL_HARGA_PRODUK_SUCCESS"
export const GET_TOTAL_HARGA_PRODUK_ERROR = "MTT/GET_TOTAL_HARGA_PRODUK_ERROR"

export const GET_COMBO_TARIF_TINDAKAN = "MTT/GET_COMBO_TARIF_TINDAKAN"
export const GET_COMBO_TARIF_TINDAKAN_SUCCESS = "MTT/GET_COMBO_TARIF_TINDAKAN_SUCCESS"
export const GET_COMBO_TARIF_TINDAKAN_ERROR = "MTT/GET_COMBO_TARIF_TINDAKAN_ERROR"

