
export const GET_ORDER_RESEP_QUERY = "GET_ORDER_RESEP_QUERY"
export const GET_ORDER_RESEP_QUERY_SUCCESS = "GET_ORDER_RESEP_QUERY_SUCCESS"
export const GET_ORDER_RESEP_QUERY_ERROR = "GET_ORDER_RESEP_QUERY_ERROR"

export const GET_ORDER_RESEP_FROM_NOREC = "GET_ORDER_RESEP_FROM_NOREC"
export const GET_ORDER_RESEP_FROM_NOREC_SUCCESS = "GET_ORDER_RESEP_FROM_NOREC_SUCCESS"
export const GET_ORDER_RESEP_FROM_NOREC_ERROR = "GET_ORDER_RESEP_FROM_NOREC_ERROR"

export const CREATE_OR_UPDATE_VERIF_RESEP = "FARMASI/CREATE_OR_UPDATE_VERIF_RESEP"
export const CREATE_OR_UPDATE_VERIF_RESEP_SUCCESS = "FARMASI/CREATE_OR_UPDATE_VERIF_RESEP_SUCCESS"
export const CREATE_OR_UPDATE_VERIF_RESEP_ERROR = "FARMASI/CREATE_OR_UPDATE_VERIF_RESEP_ERROR"

export const CREATE_OR_UPDATE_PENJUALAN_BEBAS = "FARMASI/CREATE_OR_UPDATE_PENJUALAN_BEBAS"
export const CREATE_OR_UPDATE_PENJUALAN_BEBAS_SUCCESS = "FARMASI/CREATE_OR_UPDATE_PENJUALAN_BEBAS_SUCCESS"
export const CREATE_OR_UPDATE_PENJUALAN_BEBAS_ERROR = "FARMASI/CREATE_OR_UPDATE_PENJUALAN_BEBAS_ERROR"

export const GET_PASIEN_FROM_NOCM = "FARMASI/GET_PASIEN_FROM_NOCM"
export const GET_PASIEN_FROM_NOCM_SUCCESS = "FARMASI/GET_PASIEN_FROM_NOCM_SUCCESS"
export const GET_PASIEN_FROM_NOCM_ERROR = "FARMASI/GET_PASIEN_FROM_NOCM_ERROR"

export const GET_ALL_VERIF_RESEP = "FARMASI/GET_ALL_VERIF_RESEP"
export const GET_ALL_VERIF_RESEP_SUCCESS = "FARMASI/GET_ALL_VERIF_RESEP_SUCCESS"
export const GET_ALL_VERIF_RESEP_ERROR = "FARMASI/GET_ALL_VERIF_RESEP_ERROR"

export const CREATE_OR_UPDATE_RETUR = "FARMASI/CREATE_OR_UPDATE_RETUR"
export const CREATE_OR_UPDATE_RETUR_SUCCESS = "FARMASI/CREATE_OR_UPDATE_RETUR_SUCCESS"
export const CREATE_OR_UPDATE_RETUR_ERROR = "FARMASI/CREATE_OR_UPDATE_RETUR_ERROR"

export const GET_ANTREAN_FROM_DP = "FARMASI/GET_ANTREAN_FROM_DP"
export const GET_ANTREAN_FROM_DP_SUCCESS = "FARMASI/GET_ANTREAN_FROM_DP_SUCCESS"
export const GET_ANTREAN_FROM_DP_ERROR = "FARMASI/GET_ANTREAN_FROM_DP_ERROR"

export const CREATE_OR_UPDATE_ORDER_PLUS_VERIF = "FARMASI/CREATE_OR_UPDATE_ORDER_PLUS_VERIF"
export const CREATE_OR_UPDATE_ORDER_PLUS_VERIF_SUCCESS = "FARMASI/CREATE_OR_UPDATE_ORDER_PLUS_VERIF_SUCCESS"
export const CREATE_OR_UPDATE_ORDER_PLUS_VERIF_ERROR = "FARMASI/CREATE_OR_UPDATE_ORDER_PLUS_VERIF_ERROR"