
export const GET_ORDER_RESEP_QUERY = "GET_ORDER_RESEP_QUERY"
export const GET_ORDER_RESEP_QUERY_SUCCESS = "GET_ORDER_RESEP_QUERY_SUCCESS"
export const GET_ORDER_RESEP_QUERY_ERROR = "GET_ORDER_RESEP_QUERY_ERROR"