
export const GET_ORDER_RESEP_QUERY = "GET_ORDER_RESEP_QUERY"
export const GET_ORDER_RESEP_QUERY_SUCCESS = "GET_ORDER_RESEP_QUERY_SUCCESS"
export const GET_ORDER_RESEP_QUERY_ERROR = "GET_ORDER_RESEP_QUERY_ERROR"

export const GET_ORDER_RESEP_FROM_NOREC = "GET_ORDER_RESEP_FROM_NOREC"
export const GET_ORDER_RESEP_FROM_NOREC_SUCCESS = "GET_ORDER_RESEP_FROM_NOREC_SUCCESS"
export const GET_ORDER_RESEP_FROM_NOREC_ERROR = "GET_ORDER_RESEP_FROM_NOREC_ERROR"

export const CREATE_OR_UPDATE_VERIF_RESEP = "FARMASI/CREATE_OR_UPDATE_VERIF_RESEP"
export const CREATE_OR_UPDATE_VERIF_RESEP_SUCCESS = "FARMASI/CREATE_OR_UPDATE_VERIF_RESEP_SUCCESS"
export const CREATE_OR_UPDATE_VERIF_RESEP_ERROR = "FARMASI/CREATE_OR_UPDATE_VERIF_RESEP_ERROR"