export const GUDANG_RESET = "GUDANG_RESET";

export const REGISTRASI_SAVE = "REGISTRASI_SAVE";
export const REGISTRASI_SAVE_SUCCESS = "REGISTRASI_SAVE_SUCCESS";
export const REGISTRASI_SAVE_ERROR = "REGISTRASI_SAVE_ERROR";

export const OBAT_GUDANG_SAVE = "OBAT_GUDANG_SAVE";
export const OBAT_GUDANG_SAVE_SUCCESS = "OBAT_GUDANG_SAVE_SUCCESS";
export const OBAT_GUDANG_SAVE_ERROR = "OBAT_GUDANG_SAVE_ERROR";

export const LAIN_LAIN_GET = "LAIN_LAIN_GET";
export const LAIN_LAIN_GET_SUCCESS = "LAIN_LAIN_GET_SUCCESS";
export const LAIN_LAIN_GET_ERROR = "LAIN_LAIN_GET_ERROR";

export const DETAIL_PRODUK_SAVE_OR_UPDATE = "DETAIL_PRODUK_SAVE_OR_UPDATE";
export const DETAIL_PRODUK_SAVE_OR_UPDATE_SUCCESS = "DETAIL_PRODUK_SAVE_OR_UPDATE_SUCCESS";
export const DETAIL_PRODUK_SAVE_OR_UPDATE_ERROR = "DETAIL_PRODUK_SAVE_OR_UPDATE_ERROR";

export const SEDIAAN_SAVE_OR_UPDATE = "SEDIAAN_SAVE_OR_UPDATE";
export const SEDIAAN_SAVE_OR_UPDATE_SUCCESS = "SEDIAAN_SAVE_OR_UPDATE_SUCCESS";
export const SEDIAAN_SAVE_OR_UPDATE_ERROR = "SEDIAAN_SAVE_OR_UPDATE_ERROR";

export const SATUAN_SAVE_OR_UPDATE = "SATUAN_SAVE_OR_UPDATE";
export const SATUAN_SAVE_OR_UPDATE_SUCCESS = "SATUAN_SAVE_OR_UPDATE_SUCCESS";
export const SATUAN_SAVE_OR_UPDATE_ERROR = "SATUAN_SAVE_OR_UPDATE_ERROR";

export const KONVERSI_PRODUK_QUERY_GET = "KONVERSI_PRODUK_QUERY_GET";
export const KONVERSI_PRODUK_QUERY_GET_SUCCESS = "KONVERSI_PRODUK_QUERY_GET_SUCCESS";
export const KONVERSI_PRODUK_QUERY_GET_ERROR = "KONVERSI_PRODUK_QUERY_GET_ERROR";

export const KONVERSI_KEMASAN_QUERY_GET = "KONVERSI_KEMASAN_QUERY_GET";
export const KONVERSI_KEMASAN_QUERY_GET_SUCCESS = "KONVERSI_KEMASAN_QUERY_GET_SUCCESS";
export const KONVERSI_KEMASAN_QUERY_GET_ERROR = "KONVERSI_KEMASAN_QUERY_GET_ERROR";

export const KEMASAN_SAVE_OR_UPDATE = "KEMASAN_SAVE_OR_UPDATE";
export const KEMASAN_SAVE_OR_UPDATE_SUCCESS = "KEMASAN_SAVE_OR_UPDATE_SUCCESS";
export const KEMASAN_SAVE_OR_UPDATE_ERROR = "KEMASAN_SAVE_OR_UPDATE_ERROR";

export const PRODUK_MASTER_GET = "PRODUK_MASTER_GET";
export const PRODUK_MASTER_GET_SUCCESS = "PRODUK_MASTER_GET_SUCCESS";
export const PRODUK_MASTER_GET_ERROR = "PRODUK_MASTER_GET_ERROR";

export const PRODUK_EDIT_GET = "PRODUK_EDIT_GET";
export const PRODUK_EDIT_GET_SUCCESS = "PRODUK_EDIT_GET_SUCCESS";
export const PRODUK_EDIT_GET_ERROR = "PRODUK_EDIT_GET_ERROR";

export const SATUAN_FROM_PRODUK_GET = "SATUAN_FROM_PRODUK_GET";
export const SATUAN_FROM_PRODUK_GET_SUCCESS = "SATUAN_FROM_PRODUK_GET_SUCCESS";
export const SATUAN_FROM_PRODUK_GET_ERROR = "SATUAN_FROM_PRODUK_GET_ERROR";

export const PENERIMAAN_SAVE_OR_UPDATE = "PENERIMAAN_SAVE_OR_UPDATE";
export const PENERIMAAN_SAVE_OR_UPDATE_SUCCESS = "PENERIMAAN_SAVE_OR_UPDATE_SUCCESS";
export const PENERIMAAN_SAVE_OR_UPDATE_ERROR = "PENERIMAAN_SAVE_OR_UPDATE_ERROR";

export const PENERIMAAN_QUERY_GET = "PENERIMAAN_QUERY_GET";
export const PENERIMAAN_QUERY_GET_SUCCESS = "PENERIMAAN_QUERY_GET_SUCCESS";
export const PENERIMAAN_QUERY_GET_ERROR = "PENERIMAAN_QUERY_GET_ERROR";

export const PENERIMAAN_LIST_QUERY_GET = "PENERIMAAN_LIST_QUERY_GET";
export const PENERIMAAN_LIST_QUERY_GET_SUCCESS = "PENERIMAAN_LIST_QUERY_GET_SUCCESS";
export const PENERIMAAN_LIST_QUERY_GET_ERROR = "PENERIMAAN_LIST_QUERY_GET_ERROR";

export const SETTING_GUDANG_RESET_FORM = "SETTING_GUDANG_RESET_FORM";
