export const GUDANG_RESET = "GUDANG_RESET";

export const REGISTRASI_SAVE = "REGISTRASI_SAVE";
export const REGISTRASI_SAVE_SUCCESS = "REGISTRASI_SAVE_SUCCESS";
export const REGISTRASI_SAVE_ERROR = "REGISTRASI_SAVE_ERROR";

export const OBAT_GUDANG_SAVE = "OBAT_GUDANG_SAVE";
export const OBAT_GUDANG_SAVE_SUCCESS = "OBAT_GUDANG_SAVE_SUCCESS";
export const OBAT_GUDANG_SAVE_ERROR = "OBAT_GUDANG_SAVE_ERROR";

export const LAIN_LAIN_GET = "LAIN_LAIN_GET";
export const LAIN_LAIN_GET_SUCCESS = "LAIN_LAIN_GET_SUCCESS";
export const LAIN_LAIN_GET_ERROR = "LAIN_LAIN_GET_ERROR";

export const DETAIL_PRODUK_SAVE_OR_UPDATE = "DETAIL_PRODUK_SAVE_OR_UPDATE";
export const DETAIL_PRODUK_SAVE_OR_UPDATE_SUCCESS = "DETAIL_PRODUK_SAVE_OR_UPDATE_SUCCESS";
export const DETAIL_PRODUK_SAVE_OR_UPDATE_ERROR = "DETAIL_PRODUK_SAVE_OR_UPDATE_ERROR";

export const SEDIAAN_SAVE_OR_UPDATE = "SEDIAAN_SAVE_OR_UPDATE";
export const SEDIAAN_SAVE_OR_UPDATE_SUCCESS = "SEDIAAN_SAVE_OR_UPDATE_SUCCESS";
export const SEDIAAN_SAVE_OR_UPDATE_ERROR = "SEDIAAN_SAVE_OR_UPDATE_ERROR";

export const SATUAN_SAVE_OR_UPDATE = "SATUAN_SAVE_OR_UPDATE";
export const SATUAN_SAVE_OR_UPDATE_SUCCESS = "SATUAN_SAVE_OR_UPDATE_SUCCESS";
export const SATUAN_SAVE_OR_UPDATE_ERROR = "SATUAN_SAVE_OR_UPDATE_ERROR";

export const KONVERSI_PRODUK_QUERY_GET = "KONVERSI_PRODUK_QUERY_GET";
export const KONVERSI_PRODUK_QUERY_GET_SUCCESS = "KONVERSI_PRODUK_QUERY_GET_SUCCESS";
export const KONVERSI_PRODUK_QUERY_GET_ERROR = "KONVERSI_PRODUK_QUERY_GET_ERROR";

export const KONVERSI_KEMASAN_QUERY_GET = "KONVERSI_KEMASAN_QUERY_GET";
export const KONVERSI_KEMASAN_QUERY_GET_SUCCESS = "KONVERSI_KEMASAN_QUERY_GET_SUCCESS";
export const KONVERSI_KEMASAN_QUERY_GET_ERROR = "KONVERSI_KEMASAN_QUERY_GET_ERROR";

export const KEMASAN_SAVE_OR_UPDATE = "KEMASAN_SAVE_OR_UPDATE";
export const KEMASAN_SAVE_OR_UPDATE_SUCCESS = "KEMASAN_SAVE_OR_UPDATE_SUCCESS";
export const KEMASAN_SAVE_OR_UPDATE_ERROR = "KEMASAN_SAVE_OR_UPDATE_ERROR";

export const PRODUK_MASTER_GET = "PRODUK_MASTER_GET";
export const PRODUK_MASTER_GET_SUCCESS = "PRODUK_MASTER_GET_SUCCESS";
export const PRODUK_MASTER_GET_ERROR = "PRODUK_MASTER_GET_ERROR";

export const PRODUK_EDIT_GET = "PRODUK_EDIT_GET";
export const PRODUK_EDIT_GET_SUCCESS = "PRODUK_EDIT_GET_SUCCESS";
export const PRODUK_EDIT_GET_ERROR = "PRODUK_EDIT_GET_ERROR";

export const KEMASAN_FROM_PRODUK_GET = "KEMASAN_FROM_PRODUK_GET";
export const KEMASAN_FROM_PRODUK_GET_SUCCESS = "KEMASAN_FROM_PRODUK_GET_SUCCESS";
export const KEMASAN_FROM_PRODUK_GET_ERROR = "KEMASAN_FROM_PRODUK_GET_ERROR";

export const PENERIMAAN_SAVE_OR_UPDATE = "PENERIMAAN_SAVE_OR_UPDATE";
export const PENERIMAAN_SAVE_OR_UPDATE_SUCCESS = "PENERIMAAN_SAVE_OR_UPDATE_SUCCESS";
export const PENERIMAAN_SAVE_OR_UPDATE_ERROR = "PENERIMAAN_SAVE_OR_UPDATE_ERROR";

export const UPSERT_RETUR_BARANG = "GUDANG/USPERT_RETUR_BARANG";
export const UPSERT_RETUR_BARANG_SUCCESS = "GUDANG/UPSERT_RETUR_BARANG_SUCCESS"
export const UPSERT_RETUR_BARANG_ERROR = "GUDANG/UPSERT_RETUR_BARANG_ERROR"

export const PENERIMAAN_QUERY_GET = "PENERIMAAN_QUERY_GET";
export const PENERIMAAN_QUERY_GET_SUCCESS = "PENERIMAAN_QUERY_GET_SUCCESS";
export const PENERIMAAN_QUERY_GET_ERROR = "PENERIMAAN_QUERY_GET_ERROR";

export const PENERIMAAN_LIST_QUERY_GET = "PENERIMAAN_LIST_QUERY_GET";
export const PENERIMAAN_LIST_QUERY_GET_SUCCESS = "PENERIMAAN_LIST_QUERY_GET_SUCCESS";
export const PENERIMAAN_LIST_QUERY_GET_ERROR = "PENERIMAAN_LIST_QUERY_GET_ERROR";

export const KARTU_STOK_QUERY_GET = "KARTU_STOK_QUERY_GET";
export const KARTU_STOK_QUERY_GET_SUCCESS = "KARTU_STOK_QUERY_GET_SUCCESS";
export const KARTU_STOK_QUERY_GET_ERROR = "KARTU_STOK_QUERY_GET_ERROR";

export const SETTING_GUDANG_RESET_FORM = "SETTING_GUDANG_RESET_FORM";

export const GET_STOK_UNIT_GUDANG = "GET_STOK_UNIT_GUDANG";
export const GET_STOK_UNIT_GUDANG_SUCCESS = "GET_STOK_UNIT_GUDANG_SUCCESS";
export const GET_STOK_UNIT_GUDANG_ERROR = "GET_STOK_UNIT_GUDANG_ERROR";

export const CREATE_OR_UPDATE_STOK_OPNAME = "CREATE_OR_UPDATE_STOK_OPNAME";
export const CREATE_OR_UPDATE_STOK_OPNAME_SUCCESS = "CREATE_OR_UPDATE_STOK_OPNAME_SUCCESS";
export const CREATE_OR_UPDATE_STOK_OPNAME_ERROR = "CREATE_OR_UPDATE_STOK_OPNAME_ERROR";

export const GET_STOK_OPNAME = "GET_STOK_OPNAME";
export const GET_STOK_OPNAME_SUCCESS = "GET_STOK_OPNAME_SUCCESS";
export const GET_STOK_OPNAME_ERROR = "GET_STOK_OPNAME_ERROR";

export const GET_STOK_OPNAME_DETAIL = "GET_STOK_OPNAME_DETAIL";
export const GET_STOK_OPNAME_DETAIL_SUCCESS = "GET_STOK_OPNAME_DETAIL_SUCCESS";
export const GET_STOK_OPNAME_DETAIL_ERROR = "GET_STOK_OPNAME_DETAIL_ERROR";

export const UPDATE_STOK_OPNAME_DETAILS = "UPDATE_STOK_OPNAME_DETAILS";
export const UPDATE_STOK_OPNAME_DETAILS_SUCCESS = "UPDATE_STOK_OPNAME_DETAILS_SUCCESS";
export const UPDATE_STOK_OPNAME_DETAILS_ERROR = "UPDATE_STOK_OPNAME_DETAILS_ERROR";

export const CREATE_OR_UPDATE_PEMESANAN = "GUDANG/CREATE_OR_UPDATE_PEMESANAN";
export const CREATE_OR_UPDATE_PEMESANAN_SUCCESS = "GUDANG/CREATE_OR_UPDATE_PEMESANAN_SUCCESS";
export const CREATE_OR_UPDATE_PEMESANAN_ERROR = "GUDANG/CREATE_OR_UPDATE_PEMESANAN_ERROR";

export const GET_PEMESANAN = "GUDANG/GET_PEMESANAN";
export const GET_PEMESANAN_SUCCESS = "GUDANG/GET_PEMESANAN_SUCCESS";
export const GET_PEMESANAN_ERROR = "GUDANG/GET_PEMESANAN_ERROR";

export const GET_LIST_PEMESANAN = "GUDANG/GET_LIST_PEMESANAN";
export const GET_LIST_PEMESANAN_SUCCESS = "GUDANG/GET_LIST_PEMESANAN_SUCCESS";
export const GET_LIST_PEMESANAN_ERROR = "GUDANG/GET_LIST_PEMESANAN_ERROR";

export const GET_UNIT_USER = "GUDANG/GET_UNIT_USER";
export const GET_UNIT_USER_SUCCESS = "GUDANG/GET_UNIT_USER_SUCCESS"
export const GET_UNIT_USER_ERROR = "GUDANG/GET_UNIT_USER_ERROR"

export const GET_COMBO_KARTU_STOK = "GUDANG/GET_COMBO_KARTU_STOK"
export const GET_COMBO_KARTU_STOK_SUCCESS = "GUDANG/GET_COMBO_KARTU_STOK_SUCCESS"
export const GET_COMBO_KARTU_STOK_ERROR = "GUDANG/GET_COMBO_KARTU_STOK_ERROR"

export const GET_COMBO_STOK_UNIT = "GUDANG/GET_COMBO_STOK_UNIT"
export const GET_COMBO_STOK_UNIT_SUCCESS = "GUDANG/GET_COMBO_STOK_UNIT_SUCCESS"
export const GET_COMBO_STOK_UNIT_ERROR = "GUDANG/GET_COMBO_STOK_ERROR"

