export const GUDANG_RESET = "GUDANG_RESET";

export const REGISTRASI_SAVE = "REGISTRASI_SAVE";
export const REGISTRASI_SAVE_SUCCESS = "REGISTRASI_SAVE_SUCCESS";
export const REGISTRASI_SAVE_ERROR = "REGISTRASI_SAVE_ERROR";

export const OBAT_GUDANG_SAVE = "OBAT_GUDANG_SAVE";
export const OBAT_GUDANG_SAVE_SUCCESS = "OBAT_GUDANG_SAVE_SUCCESS";
export const OBAT_GUDANG_SAVE_ERROR = "OBAT_GUDANG_SAVE_ERROR";

export const LAIN_LAIN_GET = "LAIN_LAIN_GET";
export const LAIN_LAIN_GET_SUCCESS = "LAIN_LAIN_GET_SUCCESS";
export const LAIN_LAIN_GET_ERROR = "LAIN_LAIN_GET_ERROR";

export const SETTING_GUDANG_RESET_FORM = "SETTING_GUDANG_RESET_FORM";
