
export const GET_USER_LOGIN = "LOGIN/GET_USER_LOGIN";

export const LOGIN_USER = "LOGIN/LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN/LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN/LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGIN/LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGIN/LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGIN/LOGOUT_USER_ERROR";

export const SIGNUP_USER = "LOGIN/SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "LOGIN/SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_ERROR = "LOGIN/SIGNUP_USER_ERROR";

export const GET_RIWAYAT_REGISTRASI = "REGISTRASI/GET_RIWAYAT_REGISTRASI";
export const GET_RIWAYAT_REGISTRASI_SUCCESS = "REGISTRASI/GET_RIWAYAT_REGISTRASI_SUCCESS";
export const GET_RIWAYAT_REGISTRASI_ERROR = "REGISTRASI/GET_RIWAYAT_REGISTRASI_ERROR";

export const BATAL_REGIS = "REGISTRASI/BATAL_REGIS";
export const BATAL_REGIS_SUCCESS = "REGISTRASI/BATAL_REGIS_SUCCESS";
export const BATAL_REGIS_ERROR = "REGISTRASI/BATAL_REGIS_ERROR";

export const GET_PASIEN_EDIT = "PASIEN/GET_PASIEN_EDIT";
export const GET_PASIEN_EDIT_SUCCESS = "PASIEN/GET_PASIEN_EDIT_SUCCESS";
export const GET_PASIEN_EDIT_ERROR = "PASIEN/GET_PASIEN_EDIT_ERROR";

export const UPDATE_PASIEN = "PASIEN/UPDATE_PASIEN";
export const UPDATE_PASIEN_SUCCESS = "PASIEN/UPDATE_PASIEN_SUCCESS";
export const UPDATE_PASIEN_ERROR = "PASIEN/UPDATE_PASIEN_ERROR";

export const GET_PASIEN_AKUN = "PASIEN/GET_PASIEN_AKUN";
export const GET_PASIEN_AKUN_SUCCESS = "PASIEN/GET_PASIEN_AKUN_SUCCESS";
export const GET_PASIEN_AKUN_ERROR = "PASIEN/GET_PASIEN_AKUN_ERROR";

export const GET_COMBO_PENJAMIN = "PASIEN/GET_COMBO_PENJAMIN";
export const GET_COMBO_PENJAMIN_SUCCESS = "PASIEN/GET_COMBO_PENJAMIN_SUCCESS";
export const GET_COMBO_PENJAMIN_ERROR = "PASIEN/GET_COMBO_PENJAMIN_ERROR";

export const UPSERT_PENJAMIN = "PASIEN/UPSERT_PENJAMIN";
export const UPSERT_PENJAMIN_SUCCESS = "PASIEN/UPSERT_PENJAMIN_SUCCESS";
export const UPSERT_PENJAMIN_ERROR = "PASIEN/UPSERT_PENJAMIN_ERROR";

export const GET_PENJAMIN_PASIEN = "PASIEN/GET_PENJAMIN_PASIEN";
export const GET_PENJAMIN_PASIEN_SUCCESS = "PASIEN/GET_PENJAMIN_PASIEN_SUCCESS";
export const GET_PENJAMIN_PASIEN_ERROR = "PASIEN/GET_PENJAMIN_PASIEN_ERROR";

export const GET_ANTREAN_PEMERIKSAAN = "PASIEN/GET_ANTREAN_PEMERIKSAAN";
export const GET_ANTREAN_PEMERIKSAAN_SUCCESS = "PASIEN/GET_ANTREAN_PEMERIKSAAN_SUCCESS";
export const GET_ANTREAN_PEMERIKSAAN_ERROR = "PASIEN/GET_ANTREAN_PEMERIKSAAN_ERROR";