
export const GET_USER_LOGIN = "LOGIN/GET_USER_LOGIN";

export const LOGIN_USER = "LOGIN/LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN/LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN/LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGIN/LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGIN/LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGIN/LOGOUT_USER_ERROR";

export const SIGNUP_USER = "LOGIN/SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "LOGIN/SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_ERROR = "LOGIN/SIGNUP_USER_ERROR";

export const GET_RIWAYAT_REGISTRASI = "REGISTRASI/GET_RIWAYAT_REGISTRASI";
export const GET_RIWAYAT_REGISTRASI_SUCCESS = "REGISTRASI/GET_RIWAYAT_REGISTRASI_SUCCESS";
export const GET_RIWAYAT_REGISTRASI_ERROR = "REGISTRASI/GET_RIWAYAT_REGISTRASI_ERROR";

export const BATAL_REGIS = "REGISTRASI/BATAL_REGIS";
export const BATAL_REGIS_SUCCESS = "REGISTRASI/BATAL_REGIS_SUCCESS";
export const BATAL_REGIS_ERROR = "REGISTRASI/BATAL_REGIS_ERROR";

export const GET_PASIEN_EDIT = "PASIEN/GET_PASIEN_EDIT";
export const GET_PASIEN_EDIT_SUCCESS = "PASIEN/GET_PASIEN_EDIT_SUCCESS";
export const GET_PASIEN_EDIT_ERROR = "PASIEN/GET_PASIEN_EDIT_ERROR";