export const REGISTRASI_SET_DATA = "REGISTRASI_SET_DATA";
export const REGISTRASI_RESET_FORM = "REGISTRASI_RESET_FORM";

export const REGISTRASI_SAVE = "REGISTRASI_SAVE";
export const REGISTRASI_SAVE_SUCCESS = "REGISTRASI_SAVE_SUCCESS";
export const REGISTRASI_SAVE_ERROR = "REGISTRASI_SAVE_ERROR";

export const REGISTRASI_LIST_GET = "REGISTRASI_LIST_GET";
export const REGISTRASI_LIST_GET_SUCCESS = "REGISTRASI_LIST_GET_SUCCESS";
export const REGISTRASI_LIST_GET_ERROR = "REGISTRASI_LIST_GET_ERROR";

export const REGISTRASI_GET = "REGISTRASI_GET";
export const REGISTRASI_GET_SUCCESS = "REGISTRASI_GET_SUCCESS";
export const REGISTRASI_GET_ERROR = "REGISTRASI_GET_ERROR";