export const REGISTRASI_RESET_FORM = "REGISTRASI_RESET_FORM";

export const REGISTRASI_SAVE = "REGISTRASI_SAVE";
export const REGISTRASI_SAVE_SUCCESS = "REGISTRASI_SAVE_SUCCESS";
export const REGISTRASI_SAVE_ERROR = "REGISTRASI_SAVE_ERROR";

export const REGISTRASI_LIST_GET = "REGISTRASI_LIST_GET";
export const REGISTRASI_LIST_GET_SUCCESS = "REGISTRASI_LIST_GET_SUCCESS";
export const REGISTRASI_LIST_GET_ERROR = "REGISTRASI_LIST_GET_ERROR";

export const REGISTRASI_GET = "REGISTRASI_GET";
export const REGISTRASI_GET_SUCCESS = "REGISTRASI_GET_SUCCESS";
export const REGISTRASI_GET_ERROR = "REGISTRASI_GET_ERROR";
export const REGISTRASI_GET_RESET = "REGISTRASI_GET_RESET";

export const REGISTRASI_LIST_BYOR_GET = "REGISTRASI_LIST_BYOR_GET";
export const REGISTRASI_LIST_BYOR_GET_SUCCESS = "REGISTRASI_LIST_BYOR_GET_SUCCESS";
export const REGISTRASI_LIST_BYOR_GET_ERROR = "REGISTRASI_LIST_BYOR_GET_ERROR";

export const REGISTRASI_SAVE_RUANGAN = "REGISTRASI_SAVE_RUANGAN";
export const REGISTRASI_SAVE_RUANGAN_SUCCESS = "REGISTRASI_SAVE_RUANGAN_SUCCESS";
export const REGISTRASI_SAVE_RUANGAN_ERROR = "REGISTRASI_SAVE_RUANGAN_ERROR";
export const REGISTRASI_SAVE_RUANGAN_RESET = "REGISTRASI_SAVE_RUANGAN_RESET";
export const REGISTRASI_NOREGISTRASI_RESET_FORM ="REGISTRASI_NOREGISTRASI_RESET_FORM";

export const REGISTRASI_NOREGISTRASI_GET = "REGISTRASI_NOREGISTRASI_GET";
export const REGISTRASI_NOREGISTRASI_GET_SUCCESS = "REGISTRASI_NOREGISTRASI_GET_SUCCESS";
export const REGISTRASI_NOREGISTRASI_GET_ERROR = "REGISTRASI_NOREGISTRASI_GET_ERROR";

export const REGISTRASI_RUANGAN_NOREC_GET = "REGISTRASI_RUANGAN_NOREC_GET";
export const REGISTRASI_RUANGAN_NOREC_GET_SUCCESS = "REGISTRASI_RUANGAN_NOREC_GET_SUCCESS";
export const REGISTRASI_RUANGAN_NOREC_GET_ERROR = "REGISTRASI_RUANGAN_NOREC_GET_ERROR";
export const REGISTRASI_RUANGAN_NOREC_GET_RESET = "REGISTRASI_RUANGAN_NOREC_GET_RESET";

export const REGISTRASI_NO_BPJS_GET = "REGISTRASI_NO_BPJS_GET";
export const REGISTRASI_NO_BPJS_GET_SUCCESS = "REGISTRASI_NO_BPJS_GET_SUCCESS";
export const REGISTRASI_NO_BPJS_GET_ERROR = "REGISTRASI_NO_BPJS_GET_ERROR";

export const REGISTRASI_SAVE_PENJAMIN_FK = "REGISTRASI_SAVE_PENJAMIN_FK";
export const REGISTRASI_SAVE_PENJAMIN_FK_SUCCESS = "REGISTRASI_SAVE_PENJAMIN_FK_SUCCESS";
export const REGISTRASI_SAVE_PENJAMIN_FK_ERROR = "REGISTRASI_SAVE_PENJAMIN_FK_ERROR";