export const CASEMIX_RESET_FORM = "CASEMIX_RESET_FORM";

export const UPLOAD_IMAGE = "BERITA/UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "BERITA/UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "BERITA/UPLOAD_IMAGE_ERROR";

export const UPLOAD_BERITA = "BERITA/UPLOAD_BERITA";
export const UPLOAD_BERITA_SUCCESS = "BERITA/UPLOAD_BERITA_SUCCESS";
export const UPLOAD_BERITA_ERROR = "BERITA/UPLOAD_BERITA_ERROR";