export const CASEMIX_RESET_FORM = "CASEMIX_RESET_FORM";

export const UPLOAD_IMAGE = "BERITA/UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "BERITA/UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "BERITA/UPLOAD_IMAGE_ERROR";