export const CASEMIX_RESET_FORM = "CASEMIX_RESET_FORM";

export const LIST_CARI_PASIEN_GET = "LIST_CARI_PASIEN_GET";
export const LIST_CARI_PASIEN_GET_SUCCESS = "LIST_CARI_PASIEN_GET_SUCCESS";
export const LIST_CARI_PASIEN_GET_ERROR = "LIST_CARI_PASIEN_GET_ERROR";

export const LIST_DAFTAR_PASIEN_GET = "LIST_DAFTAR_PASIEN_GET";
export const LIST_DAFTAR_PASIEN_GET_SUCCESS = "LIST_DAFTAR_PASIEN_GET_SUCCESS";
export const LIST_DAFTAR_PASIEN_GET_ERROR = "LIST_DAFTAR_PASIEN_GET_ERROR";