export const CASEMIX_RESET_FORM = "CASEMIX_RESET_FORM";

export const LIST_CARI_PASIEN_GET = "LIST_CARI_PASIEN_GET";
export const LIST_CARI_PASIEN_GET_SUCCESS = "LIST_CARI_PASIEN_GET_SUCCESS";
export const LIST_CARI_PASIEN_GET_ERROR = "LIST_CARI_PASIEN_GET_ERROR";

export const LIST_DAFTAR_PASIEN_GET = "LIST_DAFTAR_PASIEN_GET";
export const LIST_DAFTAR_PASIEN_GET_SUCCESS = "LIST_DAFTAR_PASIEN_GET_SUCCESS";
export const LIST_DAFTAR_PASIEN_GET_ERROR = "LIST_DAFTAR_PASIEN_GET_ERROR";

export const LIST_TARIF_PASIEN_GET = "LIST_TARIF_PASIEN_GET";
export const LIST_TARIF_PASIEN_GET_SUCCESS = "LIST_TARIF_PASIEN_GET_SUCCESS";
export const LIST_TARIF_PASIEN_GET_ERROR = "LIST_TARIF_PASIEN_GET_ERROR";

export const LISTDIAGNOSAX_GET = "LISTDIAGNOSAX_GET";
export const LISTDIAGNOSAX_GET_SUCCESS = "LISTDIAGNOSAX_GET_SUCCESS";
export const LISTDIAGNOSAX_GET_ERROR = "LISTDIAGNOSAX_GET_ERROR";

export const LISTDIAGNOSAIX_GET = "LISTDIAGNOSAIX_GET";
export const LISTDIAGNOSAIX_GET_SUCCESS = "LISTDIAGNOSAIX_GET_SUCCESS";
export const LISTDIAGNOSAIX_GET_ERROR = "LISTDIAGNOSAIX_GET_ERROR";

export const BRIDGING_INACBG_SAVE = "BRIDGING_INACBG_SAVE";
export const BRIDGING_INACBG_SAVE_SUCCESS = "BRIDGING_INACBG_SAVE_SUCCESS";
export const BRIDGING_INACBG_SAVE_ERROR = "BRIDGING_INACBG_SAVE_ERROR";

export const TARIF_KLAIM_SAVE = "TARIF_KLAIM_SAVE";
export const TARIF_KLAIM_SAVE_SUCCESS = "TARIF_KLAIM_SAVE_SUCCESS";
export const TARIF_KLAIM_SAVE_ERROR = "TARIF_KLAIM_SAVE_ERROR";

export const LIST_CMGOPTIONS_GET = "LIST_CMGOPTIONS_GET";
export const LIST_CMGOPTIONS_GET_SUCCESS = "LIST_CMGOPTIONS_GET_SUCCESS";
export const LIST_CMGOPTIONS_GET_ERROR = "LIST_CMGOPTIONS_GET_ERROR";

export const STATUS_KLAIM_SAVE = "STATUS_KLAIM_SAVE";
export const STATUS_KLAIM_SAVE_SUCCESS = "STATUS_KLAIM_SAVE_SUCCESS";
export const STATUS_KLAIM_SAVE_ERROR = "STATUS_KLAIM_SAVE_ERROR";

export const TARIF_CMGOPTIONS_SAVE = "TARIF_CMGOPTIONS_SAVE";
export const TARIF_CMGOPTIONS_SAVE_SUCCESS = "TARIF_CMGOPTIONS_SAVE_SUCCESS";
export const TARIF_CMGOPTIONS_SAVE_ERROR = "TARIF_CMGOPTIONS_SAVE_ERROR";