export const KIOSK_RESET_FORM = "KIOSK_RESET_FORM";

export const GET_COMBO_KIOSK = "GET_COMBO_KIOSK";
export const GET_COMBO_KIOSK_SUCCESS = "GET_COMBO_KIOSK_SUCCESS";
export const GET_COMBO_KIOSK_ERROR = "GET_COMBO_KIOSK_ERROR";

export const GET_CARI_PASIEN_KIOSK = "GET_CARI_PASIEN_KIOSK";
export const GET_CARI_PASIEN_KIOSK_SUCCESS = "GET_CARI_PASIEN_KIOSK_SUCCESS";
export const GET_CARI_PASIEN_KIOSK_ERROR = "GET_CARI_PASIEN_KIOSK_ERROR";

export const SAVE_REGISTRASI_PASIEN_KIOSK = "SAVE_REGISTRASI_PASIEN_KIOSK";
export const SAVE_REGISTRASI_PASIEN_KIOSK_SUCCESS = "SAVE_REGISTRASI_PASIEN_KIOSK_SUCCESS";
export const SAVE_REGISTRASI_PASIEN_KIOSK_ERROR = "SAVE_REGISTRASI_PASIEN_KIOSK_ERROR";