export const KIOSK_RESET_FORM = "KIOSK_RESET_FORM";

export const GET_COMBO_KIOSK = "GET_COMBO_KIOSK";
export const GET_COMBO_KIOSK_SUCCESS = "GET_COMBO_KIOSK_SUCCESS";
export const GET_COMBO_KIOSK_ERROR = "GET_COMBO_KIOSK_ERROR";