export const GET_TEMPAT_TIDUR = "SYS/GET_TEMPAT_TIDUR";
export const GET_TEMPAT_TIDUR_SUCCESS = "SYS/GET_TEMPAT_TIDUR_SUCCESS";
export const GET_TEMPAT_TIDUR_ERROR = "SYS/GET_TEMPAT_TIDUR_ERROR";

export const GET_UNIT_TEMPAT_TIDUR = "SYS/GET_UNIT_TEMPAT_TIDUR";
export const GET_UNIT_TEMPAT_TIDUR_SUCCESS = "SYS/GET_UNIT_TEMPAT_TIDUR_SUCCESS";
export const GET_UNIT_TEMPAT_TIDUR_ERROR = "SYS/GET_UNIT_TEMPAT_TIDUR_ERROR";

export const GET_COMBO_TEMPAT_TIDUR = "SYS/GET_COMBO_TEMPAT_TIDUR";
export const GET_COMBO_TEMPAT_TIDUR_SUCCESS = "SYS/GET_COMBO_TEMPAT_TIDUR_SUCCESS";
export const GET_COMBO_TEMPAT_TIDUR_ERROR = "SYS/GET_COMBO_TEMPAT_TIDUR_ERROR";

export const UPSERT_TEMPAT_TIDUR = "SYS/UPSERT_TEMPAT_TIDUR";
export const UPSERT_TEMPAT_TIDUR_SUCCESS = "SYS/UPSERT_TEMPAT_TIDUR_SUCCESS";
export const UPSERT_TEMPAT_TIDUR_ERROR = "SYS/UPSERT_TEMPAT_TIDUR_ERROR";

export const GET_ALL_UNIT = "SYS/GET_ALL_UNIT";
export const GET_ALL_UNIT_SUCCESS = "SYS/GET_ALL_UNIT_SUCCESS";
export const GET_ALL_UNIT_ERROR = "SYS/GET_ALL_UNIT_ERROR";

export const GET_COMBO_DAFTAR_UNIT = "SYS/GET_COMBO_DAFTAR_UNIT";
export const GET_COMBO_DAFTAR_UNIT_SUCCESS = "SYS/GET_COMBO_DAFTAR_UNIT_SUCCESS";
export const GET_COMBO_DAFTAR_UNIT_ERROR = "SYS/GET_COMBO_DAFTAR_UNIT_ERROR";

export const UPSERT_UNIT = "SYS/UPSERT_UNIT";
export const UPSERT_UNIT_SUCCESS = "SYS/UPSERT_UNIT_SUCCESS";
export const UPSERT_UNIT_ERROR = "SYS/UPSERT_UNIT_ERROR";

export const GET_ALL_KAMAR = "SYS/GET_ALL_KAMAR";
export const GET_ALL_KAMAR_SUCCESS = "SYS/GET_ALL_KAMAR_SUCCESS";
export const GET_ALL_KAMAR_ERROR = "SYS/GET_ALL_KAMAR_ERROR";

export const GET_COMBO_DAFTAR_KAMAR = "SYS/GET_COMBO_DAFTAR_KAMAR";
export const GET_COMBO_DAFTAR_KAMAR_SUCCESS = "SYS/GET_COMBO_DAFTAR_KAMAR_SUCCESS";
export const GET_COMBO_DAFTAR_KAMAR_ERROR = "SYS/GET_COMBO_DAFTAR_KAMAR_ERROR";

export const GET_COMBO_SYSADMIN = "SYS/GET_COMBO_SYSADMIN";
export const GET_COMBO_SYSADMIN_SUCCESS = "SYS/GET_COMBO_SYSADMIN_SUCCESS";
export const GET_COMBO_SYSADMIN_ERROR = "SYS/GET_COMBO_SYSADMIN_ERROR";

export const UPSERT_ROLES = "SYS/UPSERT_ROLES";
export const UPSERT_ROLES_SUCCESS = "SYS/UPSERT_ROLES_SUCCESS";
export const UPSERT_ROLES_ERROR = "SYS/UPSERT_ROLES_ERROR";

export const UPSERT_KAMAR = "SYS/UPSERT_KAMAR";
export const UPSERT_KAMAR_SUCCESS = "SYS/UPSERT_KAMAR_SUCCESS";
export const UPSERT_KAMAR_ERROR = "SYS/UPSERT_KAMAR_ERROR";

export const GET_MAP_ROLE_PERMISSIONS = "SYS/GET_MAP_ROLE_PERMISSIONS";
export const GET_MAP_ROLE_PERMISSIONS_SUCCESS = "SYS/GET_MAP_ROLE_PERMISSIONS_SUCCESS";
export const GET_MAP_ROLE_PERMISSIONS_ERROR = "SYS/GET_MAP_ROLE_PERMISSIONS_ERROR";

export const UPSERT_ROLE_PERMISSIONS = "SYS/UPSERT_ROLE_PERMISSIONS";
export const UPSERT_ROLE_PERMISSIONS_SUCCESS = "SYS/UPSERT_ROLE_PERMISSIONS_SUCCESS";
export const UPSERT_ROLE_PERMISSIONS_ERROR = "SYS/UPSERT_ROLE_PERMISSIONS_ERROR";

export const UPSERT_MENU_MODUL = "SYS/UPSERT_MENU_MODUL";
export const UPSERT_MENU_MODUL_SUCCESS = "SYS/UPSERT_MENU_MODUL_SUCCESS";
export const UPSERT_MENU_MODUL_ERROR = "SYS/UPSERT_MENU_MODUL_ERROR";

export const GET_MAP_CHILD = "SYS/GET_MAP_CHILD";
export const GET_MAP_CHILD_SUCCESS = "SYS/GET_MAP_CHILD_SUCCESS";
export const GET_MAP_CHILD_ERROR = "SYS/GET_MAP_CHILD_ERROR";

export const UPSERT_MAP_CHILD = "SYS/UPSERT_MAP_CHILD";
export const UPSERT_MAP_CHILD_SUCCESS = "SYS/UPSERT_MAP_CHILD_SUCCESS";
export const UPSERT_MAP_CHILD_ERROR = "SYS/UPSERT_MAP_CHILD_ERROR";