export const GET_TEMPAT_TIDUR = "TT/GET_TEMPAT_TIDUR";
export const GET_TEMPAT_TIDUR_SUCCESS = "TT/GET_TEMPAT_TIDUR_SUCCESS";
export const GET_TEMPAT_TIDUR_ERROR = "TT/GET_TEMPAT_TIDUR_ERROR";

export const GET_UNIT_TEMPAT_TIDUR = "TT/GET_UNIT_TEMPAT_TIDUR";
export const GET_UNIT_TEMPAT_TIDUR_SUCCESS = "TT/GET_UNIT_TEMPAT_TIDUR_SUCCESS";
export const GET_UNIT_TEMPAT_TIDUR_ERROR = "TT/GET_UNIT_TEMPAT_TIDUR_ERROR";

export const GET_COMBO_TEMPAT_TIDUR = "TT/GET_COMBO_TEMPAT_TIDUR";
export const GET_COMBO_TEMPAT_TIDUR_SUCCESS = "TT/GET_COMBO_TEMPAT_TIDUR_SUCCESS";
export const GET_COMBO_TEMPAT_TIDUR_ERROR = "TT/GET_COMBO_TEMPAT_TIDUR_ERROR";

export const UPSERT_TEMPAT_TIDUR = "TT/UPSERT_TEMPAT_TIDUR";
export const UPSERT_TEMPAT_TIDUR_SUCCESS = "TT/UPSERT_TEMPAT_TIDUR_SUCCESS";
export const UPSERT_TEMPAT_TIDUR_ERROR = "TT/UPSERT_TEMPAT_TIDUR_ERROR";

export const GET_ALL_UNIT = "TT/GET_ALL_UNIT";
export const GET_ALL_UNIT_SUCCESS = "TT/GET_ALL_UNIT_SUCCESS";
export const GET_ALL_UNIT_ERROR = "TT/GET_ALL_UNIT_ERROR";

export const GET_COMBO_DAFTAR_UNIT = "TT/GET_COMBO_DAFTAR_UNIT";
export const GET_COMBO_DAFTAR_UNIT_SUCCESS = "TT/GET_COMBO_DAFTAR_UNIT_SUCCESS";
export const GET_COMBO_DAFTAR_UNIT_ERROR = "TT/GET_COMBO_DAFTAR_UNIT_ERROR";

export const UPSERT_UNIT = "TT/UPSERT_UNIT";
export const UPSERT_UNIT_SUCCESS = "TT/UPSERT_UNIT_SUCCESS";
export const UPSERT_UNIT_ERROR = "TT/UPSERT_UNIT_ERROR";

export const GET_ALL_KAMAR = "TT/GET_ALL_KAMAR";
export const GET_ALL_KAMAR_SUCCESS = "TT/GET_ALL_KAMAR_SUCCESS";
export const GET_ALL_KAMAR_ERROR = "TT/GET_ALL_KAMAR_ERROR";

export const GET_COMBO_DAFTAR_KAMAR = "TT/GET_COMBO_DAFTAR_KAMAR";
export const GET_COMBO_DAFTAR_KAMAR_SUCCESS = "TT/GET_COMBO_DAFTAR_KAMAR_SUCCESS";
export const GET_COMBO_DAFTAR_KAMAR_ERROR = "TT/GET_COMBO_DAFTAR_KAMAR_ERROR";