export const DAFTARPASIEN_RESET_FORM = "DAFTARPASIEN_RESET_FORM";

export const DAFTARPASIEN_RJ_GET = "DAFTARPASIEN_RJ_GET";
export const DAFTARPASIEN_RJ_GET_SUCCESS = "DAFTARPASIEN_RJ_GET_SUCCESS";
export const DAFTARPASIEN_RJ_GET_ERROR = "DAFTARPASIEN_RJ_GET_ERROR";

export const WIDGET_DAFTARPASIEN_RJ_GET = "WIDGET_DAFTARPASIEN_RJ_GET";
export const WIDGET_DAFTARPASIEN_RJ_GET_SUCCESS = "WIDGET_DAFTARPASIEN_RJ_GET_SUCCESS";
export const WIDGET_DAFTARPASIEN_RJ_GET_ERROR = "WIDGET_DAFTARPASIEN_RJ_GET_ERROR";