export const DAFTARPASIEN_RESET_FORM = "DAFTARPASIEN_RESET_FORM";

export const DAFTARPASIEN_RJ_GET = "DAFTARPASIEN_RJ_GET";
export const DAFTARPASIEN_RJ_GET_SUCCESS = "DAFTARPASIEN_RJ_GET_SUCCESS";
export const DAFTARPASIEN_RJ_GET_ERROR = "DAFTARPASIEN_RJ_GET_ERROR";

export const WIDGET_DAFTARPASIEN_RJ_GET = "WIDGET_DAFTARPASIEN_RJ_GET";
export const WIDGET_DAFTARPASIEN_RJ_GET_SUCCESS = "WIDGET_DAFTARPASIEN_RJ_GET_SUCCESS";
export const WIDGET_DAFTARPASIEN_RJ_GET_ERROR = "WIDGET_DAFTARPASIEN_RJ_GET_ERROR";

export const WIDGET_DAFTARPASIEN_RI_GET = "WIDGET_DAFTARPASIEN_RI_GET";
export const WIDGET_DAFTARPASIEN_RI_GET_SUCCESS = "WIDGET_DAFTARPASIEN_RI_GET_SUCCESS";
export const WIDGET_DAFTARPASIEN_RI_GET_ERROR = "WIDGET_DAFTARPASIEN_RI_GET_ERROR";

export const DAFTARPASIEN_RI_GET = "DAFTARPASIEN_RI_GET";
export const DAFTARPASIEN_RI_GET_SUCCESS = "DAFTARPASIEN_RI_GET_SUCCESS";
export const DAFTARPASIEN_RI_GET_ERROR = "DAFTARPASIEN_RI_GET_ERROR";

export const DAFTARPASIEN_PULANG_GET = "DAFTARPASIEN_PULANG_GET";
export const DAFTARPASIEN_PULANG_GET_SUCCESS = "DAFTARPASIEN_PULANG_GET_SUCCESS";
export const DAFTARPASIEN_PULANG_GET_ERROR = "DAFTARPASIEN_PULANG_GET_ERROR";

export const DAFTARPASIEN_RI_PULANG_SAVE = "DAFTARPASIEN_RI_PULANG_SAVE";
export const DAFTARPASIEN_RI_PULANG_SAVE_SUCCESS = "DAFTARPASIEN_RI_PULANG_SAVE_SUCCESS";
export const DAFTARPASIEN_RI_PULANG_SAVE_ERROR = "DAFTARPASIEN_RI_PULANG_SAVE_ERROR";

export const LIST_FASKES_GET = "LIST_FASKES_GET";
export const LIST_FASKES_GET_SUCCESS = "LIST_FASKES_GET_SUCCESS";
export const LIST_FASKES_GET_ERROR = "LIST_FASKES_GET_ERROR";

export const DAFTARPASIEN_NOREC_GET = "DAFTARPASIEN_NOREC_GET";
export const DAFTARPASIEN_NOREC_GET_SUCCESS = "DAFTARPASIEN_NOREC_GET_SUCCESS";
export const DAFTARPASIEN_NOREC_GET_ERROR = "DAFTARPASIEN_NOREC_GET_ERROR";
export const DAFTARPASIEN_NOREC_GET_RESET = "DAFTARPASIEN_NOREC_GET_RESET";

export const ANTREAN_NOREC_GET = "ANTREAN_NOREC_GET";
export const ANTREAN_NOREC_GET_SUCCESS = "ANTREAN_NOREC_GET_SUCCESS";
export const ANTREAN_NOREC_GET_ERROR = "ANTREAN_NOREC_GET_ERROR";
export const ANTREAN_NOREC_GET_RESET = "ANTREAN_NOREC_GET_RESET";


export const DAFTARPASIEN_REGISTRASI_GET = "DAFTARPASIEN_REGISTRASI_GET";
export const DAFTARPASIEN_REGISTRASI_GET_SUCCESS = "DAFTARPASIEN_REGISTRASI_GET_SUCCESS";
export const DAFTARPASIEN_REGISTRASI_GET_ERROR = "DAFTARPASIEN_REGISTRASI_GET_ERROR";

export const WIDGET_DAFTARPASIEN_REGISTRASI_GET = "WIDGET_DAFTARPASIEN_REGISTRASI_GET";
export const WIDGET_DAFTARPASIEN_REGISTRASI_GET_SUCCESS = "WIDGET_DAFTARPASIEN_REGISTRASI_GET_SUCCESS";
export const WIDGET_DAFTARPASIEN_REGISTRASI_GET_ERROR = "WIDGET_DAFTARPASIEN_REGISTRASI_GET_ERROR";