

export const GET_ALL_MASTER = "MASTER/GET_ALL_MASTER";
export const GET_ALL_MASTER_SUCCESS = "MASTER/GET_ALL_MASTER_SUCCESS";
export const GET_ALL_MASTER_ERROR = "MASTER/GET_ALL_MASTER_ERROR";

export const GET_DESA_KELURAHAN = "MASTER/GET_DESA_KELURAHAN";
export const GET_DESA_KELURAHAN_SUCCESS = "MASTER/GET_DESA_KELURAHAN_SUCCESS";
export const GET_DESA_KELURAHAN_ERROR = "MASTER/GET_DESA_KELURAHAN_ERROR";