


export const GET_JADWAL_DOKTER = "HOME/GET_JADWAL_DOKTER"
export const GET_JADWAL_DOKTER_SUCCESS = "HOME/GET_JADWAL_DOKTER_SUCCESS"
export const GET_JADWAL_DOKTER_ERROR = "HOME/GET_JADWAL_DOKTER_ERROR"

export const GET_COMBO_JADWAL = "HOME/GET_COMBO_JADWAL"
export const GET_COMBO_JADWAL_SUCCESS = "HOME/GET_COMBO_JADWAL_SUCCESS"
export const GET_COMBO_JADWAL_ERROR = "HOME/GET_COMBO_JADWAL_ERROR"