


export const GET_JADWAL_DOKTER = "HOME/GET_JADWAL_DOKTER"
export const GET_JADWAL_DOKTER_SUCCESS = "HOME/GET_JADWAL_DOKTER_SUCCESS"
export const GET_JADWAL_DOKTER_ERROR = "HOME/GET_JADWAL_DOKTER_ERROR"

export const GET_COMBO_JADWAL = "HOME/GET_COMBO_JADWAL"
export const GET_COMBO_JADWAL_SUCCESS = "HOME/GET_COMBO_JADWAL_SUCCESS"
export const GET_COMBO_JADWAL_ERROR = "HOME/GET_COMBO_JADWAL_ERROR"

export const GET_BERITA_HOME = "HOME/GET_BERITA_HOME"
export const GET_BERITA_HOME_SUCCESS = "HOME/GET_BERITA_HOME_SUCCESS"
export const GET_BERITA_HOME_ERROR = "HOME/GET_BERITA_HOME_ERROR"

export const GET_BERITA_QUERY = "HOME/GET_BERITA_QUERY"
export const GET_BERITA_QUERY_SUCCESS = "HOME/GET_BERITA_QUERY_SUCCESS"
export const GET_BERITA_QUERY_ERROR = "HOME/GET_BERITA_QUERY_ERROR"

export const GET_CAPTCHA = "HOME/GET_CAPTCHA"
export const GET_CAPTCHA_SUCCESS = "HOME/GET_CAPTCHA_SUCCESS"
export const GET_CAPTCHA_ERROR = "HOME/GET_CAPTCHA_ERROR"
