export const LABORATORIUM_RESET_FORM = "LABORATORIUM_RESET_FORM";

export const WIDGET_DETAIL_JENIS_PRODUK_GET = "WIDGET_DETAIL_JENIS_PRODUK_GET";
export const WIDGET_DETAIL_JENIS_PRODUK_GET_SUCCESS = "WIDGET_DETAIL_JENIS_PRODUK_GET_SUCCESS";
export const WIDGET_DETAIL_JENIS_PRODUK_GET_ERROR = "WIDGET_DETAIL_JENIS_PRODUK_GET_ERROR";

export const SAVE_ORDER_PELAYANAN_LABORATORIUM = "SAVE_ORDER_PELAYANAN_LABORATORIUM";
export const SAVE_ORDER_PELAYANAN_LABORATORIUM_SUCCESS = "SAVE_ORDER_PELAYANAN_LABORATORIUM_SUCCESS";
export const SAVE_ORDER_PELAYANAN_LABORATORIUM_ERROR = "SAVE_ORDER_PELAYANAN_LABORATORIUM_ERROR";

export const DAFTAR_ORDER_LABORATORIUM_GET = "DAFTAR_ORDER_LABORATORIUM_GET";
export const DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "DAFTAR_ORDER_LABORATORIUM_GET_ERROR";

export const WIDGET_DAFTAR_ORDER_LABORATORIUM_GET = "WIDGET_DAFTAR_ORDER_LABORATORIUM_GET";
export const WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_ERROR";

export const LIST_DAFTAR_ORDER_LABORATORIUM_GET = "LIST_DAFTAR_ORDER_LABORATORIUM_GET";
export const LIST_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "LIST_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const LIST_DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "LIST_DAFTAR_ORDER_LABORATORIUM_GET_ERROR";

export const LIST_ORDER_LABORATORIUM_BY_NOREC_GET = "LIST_ORDER_LABORATORIUM_BY_NOREC_GET";
export const LIST_ORDER_LABORATORIUM_BY_NOREC_GET_SUCCESS = "LIST_ORDER_LABORATORIUM_BY_NOREC_GET_SUCCESS";
export const LIST_ORDER_LABORATORIUM_BY_NOREC_GET_ERROR = "LIST_ORDER_LABORATORIUM_BY_NOREC_GET_ERROR";

export const UPDATE_TGLRENCANA_LABORATORIUM = "UPDATE_TGLRENCANA_LABORATORIUM";
export const UPDATE_TGLRENCANA_LABORATORIUM_SUCCESS = "UPDATE_TGLRENCANA_LABORATORIUM_SUCCESS";
export const UPDATE_TGLRENCANA_LABORATORIUM_ERROR = "UPDATE_TGLRENCANA_LABORATORIUM_ERROR";

export const SAVE_VERIFIKASI_LABORATORIUM = "SAVE_VERIFIKASI_LABORATORIUM";
export const SAVE_VERIFIKASI_LABORATORIUM_SUCCESS = "SAVE_VERIFIKASI_LABORATORIUM_SUCCESS";
export const SAVE_VERIFIKASI_LABORATORIUM_ERROR = "SAVE_VERIFIKASI_LABORATORIUM_ERROR";

export const DAFTAR_PASIEN_LABORATORIUM = "DAFTAR_PASIEN_LABORATORIUM";
export const DAFTAR_PASIEN_LABORATORIUM_SUCCESS = "DAFTAR_PASIEN_LABORATORIUM_SUCCESS";
export const DAFTAR_PASIEN_LABORATORIUM_ERROR = "DAFTAR_PASIEN_LABORATORIUM_ERROR";

export const LIST_PELAYANAN_LABORATORIUM_GET = "LIST_PELAYANAN_LABORATORIUM_GET";
export const LIST_PELAYANAN_LABORATORIUM_GET_SUCCESS = "LIST_PELAYANAN_LABORATORIUM_GET_SUCCESS";
export const LIST_PELAYANAN_LABORATORIUM_GET_ERROR = "LIST_PELAYANAN_LABORATORIUM_GET_ERROR";