export const LABORATORIUM_RESET_FORM = "LABORATORIUM_RESET_FORM";

export const WIDGET_DETAIL_JENIS_PRODUK_GET = "WIDGET_DETAIL_JENIS_PRODUK_GET";
export const WIDGET_DETAIL_JENIS_PRODUK_GET_SUCCESS = "WIDGET_DETAIL_JENIS_PRODUK_GET_SUCCESS";
export const WIDGET_DETAIL_JENIS_PRODUK_GET_ERROR = "WIDGET_DETAIL_JENIS_PRODUK_GET_ERROR";

export const SAVE_ORDER_PELAYANAN_LABORATORIUM = "SAVE_ORDER_PELAYANAN_LABORATORIUM";
export const SAVE_ORDER_PELAYANAN_LABORATORIUM_SUCCESS = "SAVE_ORDER_PELAYANAN_LABORATORIUM_SUCCESS";
export const SAVE_ORDER_PELAYANAN_LABORATORIUM_ERROR = "SAVE_ORDER_PELAYANAN_LABORATORIUM_ERROR";

export const DAFTAR_ORDER_LABORATORIUM_GET = "DAFTAR_ORDER_LABORATORIUM_GET";
export const DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "DAFTAR_ORDER_LABORATORIUM_GET_ERROR";