export const LABORATORIUM_RESET_FORM = "LABORATORIUM_RESET_FORM";

export const WIDGET_DETAIL_JENIS_PRODUK_GET = "WIDGET_DETAIL_JENIS_PRODUK_GET";
export const WIDGET_DETAIL_JENIS_PRODUK_GET_SUCCESS = "WIDGET_DETAIL_JENIS_PRODUK_GET_SUCCESS";
export const WIDGET_DETAIL_JENIS_PRODUK_GET_ERROR = "WIDGET_DETAIL_JENIS_PRODUK_GET_ERROR";

export const SAVE_ORDER_PELAYANAN_LABORATORIUM = "SAVE_ORDER_PELAYANAN_LABORATORIUM";
export const SAVE_ORDER_PELAYANAN_LABORATORIUM_SUCCESS = "SAVE_ORDER_PELAYANAN_LABORATORIUM_SUCCESS";
export const SAVE_ORDER_PELAYANAN_LABORATORIUM_ERROR = "SAVE_ORDER_PELAYANAN_LABORATORIUM_ERROR";

export const DAFTAR_ORDER_LABORATORIUM_GET = "DAFTAR_ORDER_LABORATORIUM_GET";
export const DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "DAFTAR_ORDER_LABORATORIUM_GET_ERROR";

export const WIDGET_DAFTAR_ORDER_LABORATORIUM_GET = "WIDGET_DAFTAR_ORDER_LABORATORIUM_GET";
export const WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "WIDGET_DAFTAR_ORDER_LABORATORIUM_GET_ERROR";

export const LIST_DAFTAR_ORDER_LABORATORIUM_GET = "LIST_DAFTAR_ORDER_LABORATORIUM_GET";
export const LIST_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS = "LIST_DAFTAR_ORDER_LABORATORIUM_GET_SUCCESS";
export const LIST_DAFTAR_ORDER_LABORATORIUM_GET_ERROR = "LIST_DAFTAR_ORDER_LABORATORIUM_GET_ERROR";

export const LIST_ORDER_LABORATORIUM_BY_NOREC_GET = "LIST_ORDER_LABORATORIUM_BY_NOREC_GET";
export const LIST_ORDER_LABORATORIUM_BY_NOREC_GET_SUCCESS = "LIST_ORDER_LABORATORIUM_BY_NOREC_GET_SUCCESS";
export const LIST_ORDER_LABORATORIUM_BY_NOREC_GET_ERROR = "LIST_ORDER_LABORATORIUM_BY_NOREC_GET_ERROR";

export const UPDATE_TGLRENCANA_LABORATORIUM = "UPDATE_TGLRENCANA_LABORATORIUM";
export const UPDATE_TGLRENCANA_LABORATORIUM_SUCCESS = "UPDATE_TGLRENCANA_LABORATORIUM_SUCCESS";
export const UPDATE_TGLRENCANA_LABORATORIUM_ERROR = "UPDATE_TGLRENCANA_LABORATORIUM_ERROR";

export const SAVE_VERIFIKASI_LABORATORIUM = "SAVE_VERIFIKASI_LABORATORIUM";
export const SAVE_VERIFIKASI_LABORATORIUM_SUCCESS = "SAVE_VERIFIKASI_LABORATORIUM_SUCCESS";
export const SAVE_VERIFIKASI_LABORATORIUM_ERROR = "SAVE_VERIFIKASI_LABORATORIUM_ERROR";

export const DAFTAR_PASIEN_LABORATORIUM = "DAFTAR_PASIEN_LABORATORIUM";
export const DAFTAR_PASIEN_LABORATORIUM_SUCCESS = "DAFTAR_PASIEN_LABORATORIUM_SUCCESS";
export const DAFTAR_PASIEN_LABORATORIUM_ERROR = "DAFTAR_PASIEN_LABORATORIUM_ERROR";

export const LIST_PELAYANAN_LABORATORIUM_GET = "LIST_PELAYANAN_LABORATORIUM_GET";
export const LIST_PELAYANAN_LABORATORIUM_GET_SUCCESS = "LIST_PELAYANAN_LABORATORIUM_GET_SUCCESS";
export const LIST_PELAYANAN_LABORATORIUM_GET_ERROR = "LIST_PELAYANAN_LABORATORIUM_GET_ERROR";

export const MASTER_PELAYANAN_LABORATORIUM_GET = "MASTER_PELAYANAN_LABORATORIUM_GET";
export const MASTER_PELAYANAN_LABORATORIUM_GET_SUCCESS = "MASTER_PELAYANAN_LABORATORIUM_GET_SUCCESS";
export const MASTER_PELAYANAN_LABORATORIUM_GET_ERROR = "MASTER_PELAYANAN_LABORATORIUM_GET_ERROR";

export const COMBO_LABORATORIUM_GET = "COMBO_LABORATORIUM_GET";
export const COMBO_LABORATORIUM_GET_SUCCESS = "COMBO_LABORATORIUM_GET_SUCCESS";
export const COMBO_LABORATORIUM_GET_ERROR = "COMBO_LABORATORIUM_GET_ERROR";

export const SAVE_NILAINORMAL_LABORATORIUM = "SAVE_NILAINORMAL_LABORATORIUM";
export const SAVE_NILAINORMAL_LABORATORIUM_SUCCESS = "SAVE_NILAINORMAL_LABORATORIUM_SUCCESS";
export const SAVE_NILAINORMAL_LABORATORIUM_ERROR = "SAVE_NILAINORMAL_LABORATORIUM_ERROR";

export const SAVE_MASTER_KEL_UMUR_LABORATORIUM = "SAVE_MASTER_KEL_UMUR_LABORATORIUM";
export const SAVE_MASTER_KEL_UMUR_LABORATORIUM_SUCCESS = "SAVE_MASTER_KEL_UMUR_LABORATORIUM_SUCCESS";
export const SAVE_MASTER_KEL_UMUR_LABORATORIUM_ERROR = "SAVE_MASTER_KEL_UMUR_LABORATORIUM_ERROR";

export const LIST_DETAIL_KEL_UMUR_LABORATORIUM_GET = "LIST_DETAIL_KEL_UMUR_LABORATORIUM_GET";
export const LIST_DETAIL_KEL_UMUR_LABORATORIUM_GET_SUCCESS = "LIST_DETAIL_KEL_UMUR_LABORATORIUM_GET_SUCCESS";
export const LIST_DETAIL_KEL_UMUR_LABORATORIUM_GET_ERROR = "LIST_DETAIL_KEL_UMUR_LABORATORIUM_GET_ERROR";

export const SAVE_MASTER_DKEL_UMUR_LABORATORIUM = "SAVE_MASTER_DKEL_UMUR_LABORATORIUM";
export const SAVE_MASTER_DKEL_UMUR_LABORATORIUM_SUCCESS = "SAVE_MASTER_DKEL_UMUR_LABORATORIUM_SUCCESS";
export const SAVE_MASTER_DKEL_UMUR_LABORATORIUM_ERROR = "SAVE_MASTER_DKEL_UMUR_LABORATORIUM_ERROR";
