export const MASTER_GET = "MASTER_GET";
export const MASTER_GET_SUCCESS = "MASTER_GET_SUCCESS";
export const MASTER_GET_ERROR = "MASTER_GET_ERROR";

export const DESA_GET = "DESA_GET";
export const DESA_GET_SUCCESS = "DESA_GET_SUCCESS";
export const DESA_GET_ERROR = "DESA_GET_ERROR";

export const KECAMATAN_GET = "KECAMATAN_GET";
export const KECAMATAN_GET_SUCCESS = "KECAMATAN_GET_SUCCESS";
export const KECAMATAN_GET_ERROR = "KECAMATAN_GET_ERROR";

export const COMBO_REGISTRASI_GET = "COMBO_REGISTRASI_GET";
export const COMBO_REGISTRASI_GET_SUCCESS = "COMBO_REGISTRASI_GET_SUCCESS";
export const COMBO_REGISTRASI_GET_ERROR = "COMBO_REGISTRASI_GET_ERROR";

export const COMBO_ASURANSI_GET = "COMBO_ASURANSI_GET";
export const COMBO_ASURANSI_GET_SUCCESS = "COMBO_ASURANSI_GET_SUCCESS";
export const COMBO_ASURANSI_GET_ERROR = "COMBO_ASURANSI_GET_ERROR";

export const COMBO_PULANG_GET = "COMBO_PULANG_GET";
export const COMBO_PULANG_GET_SUCCESS = "COMBO_PULANG_GET_SUCCESS";
export const COMBO_PULANG_GET_ERROR = "COMBO_PULANG_GET_ERROR";

export const PROVINSI_GET_BPJS = "PROVINSI_GET_BPJS";
export const PROVINSI_GET_BPJS_SUCCESS = "PROVINSI_GET_BPJS_SUCCESS";
export const PROVINSI_GET_BPJS_ERROR = "PROVINSI_GET_BPJS_ERROR";

export const KABUPATEN_GET_BPJS = "KABUPATEN_GET_BPJS";
export const KABUPATEN_GET_BPJS_SUCCESS = "KABUPATEN_GET_BPJS_SUCCESS";
export const KABUPATEN_GET_BPJS_ERROR = "KABUPATEN_GET_BPJS_ERROR";

export const KECAMATAN_GET_BPJS = "KECAMATAN_GET_BPJS";
export const KECAMATAN_GET_BPJS_SUCCESS = "KECAMATAN_GET_BPJS_SUCCESS";
export const KECAMATAN_GET_BPJS_ERROR = "KECAMATAN_GET_BPJS_ERROR";

export const COMBO_PAYMENT_GET = "COMBO_PAYMENT_GET";
export const COMBO_PAYMENT_GET_SUCCESS = "COMBO_PAYMENT_GET_SUCCESS";
export const COMBO_PAYMENT_GET_ERROR = "COMBO_PAYMENT_GET_ERROR";

export const COMBO_SETTING_PRODUK_GET = "COMBO_SETTING_PRODUK_GET";
export const COMBO_SETTING_PRODUK_GET_SUCCESS = "COMBO_SETTING_PRODUK_GET_SUCCESS";
export const COMBO_SETTING_PRODUK_GET_ERROR = "COMBO_SETTING_PRODUK_GET_ERROR";

export const COMBO_PENERIMAAN_BARANG_GET = "COMBO_PENERIMAAN_BARANG_GET";
export const COMBO_PENERIMAAN_BARANG_GET_SUCCESS = "COMBO_PENERIMAAN_BARANG_GET_SUCCESS";
export const COMBO_PENERIMAAN_BARANG_GET_ERROR = "COMBO_PENERIMAAN_BARANG_GET_ERROR";

export const COMBO_DISTRIBUSI_ORDER_GET = "COMBO_DISTRIBUSI_ORDER_GET";
export const COMBO_DISTRIBUSI_ORDER_GET_SUCCESS = "COMBO_DISTRIBUSI_ORDER_GET_SUCCESS";
export const COMBO_DISTRIBUSI_ORDER_GET_ERROR = "COMBO_DISTRIBUSI_ORDER_GET_ERROR";

export const GET_COMBO_STOK_OPNAME = "GET_COMBO_STOK_OPNAME";
export const GET_COMBO_STOK_OPNAME_SUCCESS = "GET_COMBO_STOK_OPNAME_SUCCESS";
export const GET_COMBO_STOK_OPNAME_ERROR = "GET_COMBO_STOK_OPNAME_ERROR";

export const GET_COMBO_RESEP = "GET_COMBO_RESEP";
export const GET_COMBO_RESEP_SUCCESS = "GET_COMBO_RESEP_SUCCESS";
export const GET_COMBO_RESEP_ERROR = "GET_COMBO_RESEP_ERROR";

export const GET_COMBO_VERIF_RESEP = "GET_COMBO_VERIF_RESEP";
export const GET_COMBO_VERIF_RESEP_SUCCESS = "GET_COMBO_VERIF_RESEP_SUCCESS";
export const GET_COMBO_VERIF_RESEP_ERROR = "GET_COMBO_VERIF_RESEP_ERROR";