export const MASTER_GET = "MASTER_GET";
export const MASTER_GET_SUCCESS = "MASTER_GET_SUCCESS";
export const MASTER_GET_ERROR = "MASTER_GET_ERROR";

export const DESA_GET = "DESA_GET";
export const DESA_GET_SUCCESS = "DESA_GET_SUCCESS";
export const DESA_GET_ERROR = "DESA_GET_ERROR";

export const KECAMATAN_GET = "KECAMATAN_GET";
export const KECAMATAN_GET_SUCCESS = "KECAMATAN_GET_SUCCESS";
export const KECAMATAN_GET_ERROR = "KECAMATAN_GET_ERROR";